(()=>{
'use strict';
const V45={sectionId:null,cellKey:null};
const q=id=>document.getElementById(id);
const esc=v=>escapeHtml(String(v??''));
const clamp=(v,a,b,d)=>{v=Number(v);return Number.isFinite(v)?Math.max(a,Math.min(b,Math.round(v))):d};
const names={ru:{layout1:'Контейнер 1',layout2:'2 колонки',layout3:'3 колонки',layout4:'4 колонки',layoutGrid:'Grid'},az:{layout1:'1 konteyner',layout2:'2 sütun',layout3:'3 sütun',layout4:'4 sütun',layoutGrid:'Grid'},en:{layout1:'1 Container',layout2:'2 Columns',layout3:'3 Columns',layout4:'4 Columns',layoutGrid:'Grid'}};
Object.entries(names).forEach(([l,n])=>Object.assign(i18n[l].blocksNames,n));
function baseStyle(){return{bg:'#ffffff',color:'#111827',padding:56,paddingX:28,width:1120,align:'left',minHeight:0,radius:0,borderWidth:0,borderColor:'#dfe3ec',shadow:'none'}}
function layoutHtml(count,d=count,t=Math.min(2,count),m=1){return `<div class="v45-layout" data-v45-layout="1" data-v45-cols-d="${d}" data-v45-cols-t="${t}" data-v45-cols-m="${m}" style="--v45-cols-d:${d};--v45-cols-t:${t};--v45-cols-m:${m};--v45-gap:20px">${Array.from({length:count},(_,i)=>`<div class="v45-cell" data-v45-cell="cell-${i+1}"></div>`).join('')}</div>`}
Object.assign(templates,{
 layout1:{icon:'▯',category:'main',html:layoutHtml(1,1,1,1),style:baseStyle()},
 layout2:{icon:'▯▯',category:'main',html:layoutHtml(2,2,2,1),style:baseStyle()},
 layout3:{icon:'▯▯▯',category:'main',html:layoutHtml(3,3,2,1),style:baseStyle()},
 layout4:{icon:'▦',category:'main',html:layoutHtml(4,4,2,1),style:baseStyle()},
 layoutGrid:{icon:'⊞',category:'main',html:layoutHtml(4,4,2,1),style:baseStyle()}
});
const isLayout=s=>!!s&&/^layout(1|2|3|4|Grid)$/.test(s.type);
function box(s){const b=document.createElement('div');b.innerHTML=s?.html||'';return b}
function layoutRoot(s,b=box(s)){return b.querySelector('.v45-layout')}
function selectedSection(){return findSection(state.selected)}
function cellFor(s,key,b=box(s)){return b.querySelector(`.v45-cell[data-v45-cell="${CSS.escape(key||'')}"]`)}
function elementNode(type){const n=document.createElement('div');n.className='custom-item v45-element';n.dataset.customType=type;n.dataset.v45Id=uid('el');if(type==='heading')n.innerHTML='<h2 contenteditable="true">New heading</h2>';else if(type==='text')n.innerHTML='<p contenteditable="true">New text</p>';else if(type==='image')n.innerHTML=`<img class="editable-image" src="${placeholderSvg('YOUR IMAGE')}" alt="Image" data-default="true">`;else if(type==='button')n.innerHTML='<a class="web-btn" href="#" contenteditable="true">Button</a>';else if(type==='divider')n.innerHTML='<hr class="content-divider">';else if(type==='spacer')n.innerHTML='<div style="height:56px"></div>';return n}
function normalizeNav(s){if(!s||s.type!=='navbar')return;const b=box(s),row=b.querySelector('.nav-row');if(!row)return;s.style||={};s.style.navLinksAlign||='center';s.style.navMobileToggle||='right';s.style.navMobilePanel||='right';s.style.navMobileCta??='hide';s.style.navGap=clamp(s.style.navGap,0,80,20);s.style.navMenuBg||='#ffffff';s.style.navMenuColor||='#111827';row.classList.add('v45-nav');row.classList.remove('v45-toggle-left','v45-toggle-center','v45-toggle-right','v45-panel-left','v45-panel-center','v45-panel-right','v45-panel-full');row.classList.add(`v45-toggle-${s.style.navMobileToggle}`,`v45-panel-${s.style.navMobilePanel}`);row.style.setProperty('--v45-links-align',s.style.navLinksAlign==='left'?'flex-start':s.style.navLinksAlign==='right'?'flex-end':'center');row.style.setProperty('--v45-nav-gap',`${s.style.navGap}px`);row.style.setProperty('--v45-menu-bg',s.style.navMenuBg);row.style.setProperty('--v45-menu-color',s.style.navMenuColor);const cta=row.querySelector(':scope>.web-btn');if(cta)cta.classList.toggle('v45-mobile-cta-hide',s.style.navMobileCta==='hide');s.html=b.innerHTML}
function normalizePricing(s){if(!s||s.type!=='pricing')return;s.style||={};s.style.priceBorder=clamp(s.style.priceBorder,0,12,1);s.style.priceRadius=clamp(s.style.priceRadius,0,80,16);s.style.priceBorderColor||='#dfe3ec';if(s.style.priceFeatured===undefined)s.style.priceFeatured=0;s.style.priceFeatured=clamp(s.style.priceFeatured,0,99,0);s.style.priceFeatureBorder=clamp(s.style.priceFeatureBorder,0,12,2);s.style.priceFeatureColor||='#705cff';s.style.priceFeatureBg||='#ffffff';const b=box(s),cards=[...b.querySelectorAll('.pricing-card')];cards.forEach((c,i)=>{c.classList.toggle('v45-featured',s.style.priceFeatured===i+1);c.classList.remove('featured');c.style.setProperty('--v45-price-border',`${s.style.priceBorder}px`);c.style.setProperty('--v45-price-border-color',s.style.priceBorderColor);c.style.setProperty('--v45-price-radius',`${s.style.priceRadius}px`);c.style.setProperty('--v45-feature-border',`${s.style.priceFeatureBorder}px`);c.style.setProperty('--v45-feature-color',s.style.priceFeatureColor);c.style.setProperty('--v45-feature-bg',s.style.priceFeatureBg)});s.html=b.innerHTML}
function normalizeLayout(s){if(!isLayout(s))return;const b=box(s),r=layoutRoot(s,b);if(!r)return;const cells=[...r.querySelectorAll(':scope>.v45-cell')];cells.forEach((c,i)=>{c.dataset.v45Cell||=`cell-${i+1}`;c.querySelectorAll('.v45-element').forEach(el=>{el.dataset.v45Id||=uid('el');el.classList.add('custom-item')})});const count=Math.max(1,cells.length);r.dataset.v45ColsD=String(clamp(r.dataset.v45ColsD,1,6,Math.min(count,4)));r.dataset.v45ColsT=String(clamp(r.dataset.v45ColsT,1,6,Math.min(count,2)));r.dataset.v45ColsM=String(clamp(r.dataset.v45ColsM,1,6,1));r.style.setProperty('--v45-cols-d',r.dataset.v45ColsD);r.style.setProperty('--v45-cols-t',r.dataset.v45ColsT);r.style.setProperty('--v45-cols-m',r.dataset.v45ColsM);r.style.setProperty('--v45-gap',`${clamp(r.dataset.v45Gap||parseFloat(r.style.getPropertyValue('--v45-gap')),0,160,20)}px`);s.html=b.innerHTML}
function normalizeAll(){if(!state.project)return;state.project.pages.forEach(p=>p.sections.forEach(s=>{normalizeNav(s);normalizePricing(s);normalizeLayout(s)}))}
function installInspector(){const form=q('inspector');if(!form||q('v45LayoutInspector'))return;const actions=form.querySelector('.inspector-actions');const layout=document.createElement('fieldset');layout.id='v45LayoutInspector';layout.className='v4-section hidden';layout.innerHTML=`<legend>Structure / Container</legend><div class="v45-cell-status" id="v45CellStatus">Select a cell</div><div class="v45-structure-picker" id="v45StructurePicker"></div><div class="v4-grid-3"><label>Columns D<input id="v45ColsD" type="number" min="1" max="6"></label><label>Columns T<input id="v45ColsT" type="number" min="1" max="6"></label><label>Columns M<input id="v45ColsM" type="number" min="1" max="6"></label></div><div class="v4-grid-2"><label>Gap px<input id="v45Gap" type="number" min="0" max="160"></label><label>2-column ratio<select id="v45Ratio"><option value="equal">50 / 50</option><option value="33-67">33 / 67</option><option value="67-33">67 / 33</option><option value="25-75">25 / 75</option><option value="75-25">75 / 25</option></select></label></div><strong style="font-size:11px">Add element to selected cell</strong><div class="v45-layout-palette" id="v45ElementPalette"><button data-v45-add="heading">+ Heading</button><button data-v45-add="text">+ Text</button><button data-v45-add="image">+ Image</button><button data-v45-add="button">+ Button</button><button data-v45-add="divider">+ Divider</button><button data-v45-add="spacer">+ Spacer</button></div><small class="v4-hint">First choose the structure, then click a cell and add elements into that cell. Elements can be dragged between cells.</small>`;
const menu=document.createElement('fieldset');menu.id='v45MenuInspector';menu.className='v4-section hidden';menu.innerHTML=`<legend>Menu placement</legend><div class="v4-grid-2"><label>Desktop links<select id="v45NavAlign"><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></label><label>Items gap px<input id="v45NavGap" type="number" min="0" max="80"></label></div><div class="v4-grid-2"><label>Mobile icon position<select id="v45TogglePos"><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></label><label>Mobile menu panel<select id="v45PanelPos"><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option><option value="full">Full width</option></select></label></div><div class="v4-grid-2"><label>Mobile CTA<select id="v45MobileCta"><option value="hide">Hide</option><option value="show">Show</option></select></label><label>Panel background<input id="v45MenuBg" type="text" placeholder="#ffffff"></label></div><label>Panel text color<input id="v45MenuColor" type="text" placeholder="#111827"></label><small class="v4-hint">This controls where the hamburger and opened mobile menu appear. Default is a compact panel aligned to the right.</small>`;
const pricing=document.createElement('fieldset');pricing.id='v45PricingInspector';pricing.className='v4-section hidden';pricing.innerHTML=`<legend>Pricing cards</legend><div class="v4-grid-3"><label>Border px<input id="v45PriceBorder" type="number" min="0" max="12"></label><label>Radius px<input id="v45PriceRadius" type="number" min="0" max="80"></label><label>Highlight<select id="v45PriceFeatured"></select></label></div><label>Border color<input id="v45PriceBorderColor" type="text" placeholder="#dfe3ec"></label><div class="v4-grid-3"><label>Highlight px<input id="v45FeatureBorder" type="number" min="0" max="12"></label><label>Highlight color<input id="v45FeatureColor" type="text" placeholder="#705cff"></label><label>Highlight bg<input id="v45FeatureBg" type="text" placeholder="#ffffff"></label></div><small class="v4-hint">No card is highlighted unless you choose it here. This removes the accidental border difference.</small>`;
form.insertBefore(layout,actions);form.insertBefore(menu,actions);form.insertBefore(pricing,actions);bindInspector();renderStructurePicker(1)}
function renderStructurePicker(active){const el=q('v45StructurePicker');if(!el)return;el.innerHTML=[1,2,3,4,6].map(n=>`<button type="button" data-v45-cells="${n}" class="${active===n?'active':''}"><span class="v45-structure-icon">${Array.from({length:Math.min(n,4)},()=>'<i></i>').join('')}</span><small>${n} cell${n>1?'s':''}</small></button>`).join('')}
function bindInspector(){q('v45StructurePicker').onclick=e=>{const b=e.target.closest('[data-v45-cells]');if(b)setCellCount(+b.dataset.v45Cells)};q('v45ElementPalette').onclick=e=>{const b=e.target.closest('[data-v45-add]');if(b)addElement(b.dataset.v45Add)};['D','T','M'].forEach(d=>q('v45Cols'+d).onchange=e=>setLayoutProp(`cols${d}`,e.target.value));q('v45Gap').onchange=e=>setLayoutProp('gap',e.target.value);q('v45Ratio').onchange=e=>setLayoutProp('ratio',e.target.value);q('v45NavAlign').onchange=e=>setNav('navLinksAlign',e.target.value);q('v45NavGap').onchange=e=>setNav('navGap',e.target.value);q('v45TogglePos').onchange=e=>setNav('navMobileToggle',e.target.value);q('v45PanelPos').onchange=e=>setNav('navMobilePanel',e.target.value);q('v45MobileCta').onchange=e=>setNav('navMobileCta',e.target.value);q('v45MenuBg').onchange=e=>setNav('navMenuBg',e.target.value);q('v45MenuColor').onchange=e=>setNav('navMenuColor',e.target.value);q('v45PriceBorder').onchange=e=>setPrice('priceBorder',e.target.value);q('v45PriceRadius').onchange=e=>setPrice('priceRadius',e.target.value);q('v45PriceBorderColor').onchange=e=>setPrice('priceBorderColor',e.target.value);q('v45PriceFeatured').onchange=e=>setPrice('priceFeatured',e.target.value);q('v45FeatureBorder').onchange=e=>setPrice('priceFeatureBorder',e.target.value);q('v45FeatureColor').onchange=e=>setPrice('priceFeatureColor',e.target.value);q('v45FeatureBg').onchange=e=>setPrice('priceFeatureBg',e.target.value)}
function setCellCount(count){const s=selectedSection();if(!isLayout(s))return;count=clamp(count,1,6,1);const b=box(s),r=layoutRoot(s,b),cells=[...r.children].filter(x=>x.classList.contains('v45-cell'));snapshot();while(cells.length<count){const c=document.createElement('div');c.className='v45-cell';c.dataset.v45Cell=`cell-${uid('c').slice(-6)}`;r.appendChild(c);cells.push(c)}while(cells.length>count){const gone=cells.pop(),target=cells.at(-1);[...gone.children].forEach(x=>target?.appendChild(x));gone.remove()}r.dataset.v45ColsD=String(Math.min(count,clamp(r.dataset.v45ColsD,1,6,count)));r.dataset.v45ColsT=String(Math.min(count,clamp(r.dataset.v45ColsT,1,6,Math.min(2,count))));r.dataset.v45ColsM=String(Math.min(count,clamp(r.dataset.v45ColsM,1,6,1)));r.style.removeProperty('--v45-template');delete r.dataset.v45Ratio;s.html=b.innerHTML;V45.sectionId=s.id;V45.cellKey=r.querySelector('.v45-cell')?.dataset.v45Cell||null;commit();renderCanvas()}
function setLayoutProp(key,value){const s=selectedSection();if(!isLayout(s))return;const b=box(s),r=layoutRoot(s,b),count=r.querySelectorAll(':scope>.v45-cell').length;snapshot();if(key.startsWith('cols')){const d=key.slice(-1).toUpperCase(),v=Math.min(count,clamp(value,1,6,1));r.dataset[`v45Cols${d}`]=String(v);r.style.setProperty(`--v45-cols-${d.toLowerCase()}`,String(v))}else if(key==='gap'){const v=clamp(value,0,160,20);r.dataset.v45Gap=String(v);r.style.setProperty('--v45-gap',`${v}px`)}else if(key==='ratio'){r.dataset.v45Ratio=value;if(count===2){const map={equal:'1fr 1fr','33-67':'1fr 2fr','67-33':'2fr 1fr','25-75':'1fr 3fr','75-25':'3fr 1fr'};r.style.setProperty('--v45-template',map[value]||map.equal)}else r.style.removeProperty('--v45-template')}s.html=b.innerHTML;commit();renderCanvas()}
function addElement(type){const s=selectedSection();if(!isLayout(s))return;const b=box(s),r=layoutRoot(s,b);let key=V45.sectionId===s.id?V45.cellKey:null;let c=cellFor(s,key,b);if(!c){c=r.querySelector('.v45-cell');key=c?.dataset.v45Cell}if(!c)return;snapshot();c.appendChild(elementNode(type));s.html=b.innerHTML;V45.sectionId=s.id;V45.cellKey=key;commit();renderCanvas()}
function setNav(key,val){const s=selectedSection();if(!s||s.type!=='navbar')return;snapshot();s.style||={};if(key==='navGap')val=clamp(val,0,80,20);s.style[key]=val;normalizeNav(s);commit();renderCanvas()}
function setPrice(key,val){const s=selectedSection();if(!s||s.type!=='pricing')return;snapshot();s.style||={};if(['priceBorder','priceRadius','priceFeatured','priceFeatureBorder'].includes(key))val=Number(val)||0;s.style[key]=val;normalizePricing(s);commit();renderCanvas()}
function updateInspector45(){installInspector();const s=selectedSection();q('v45LayoutInspector').classList.toggle('hidden',!isLayout(s));q('v45MenuInspector').classList.toggle('hidden',s?.type!=='navbar');q('v45PricingInspector').classList.toggle('hidden',s?.type!=='pricing');if(isLayout(s)){const b=box(s),r=layoutRoot(s,b),cells=[...r.querySelectorAll(':scope>.v45-cell')];if(V45.sectionId!==s.id||!cells.some(c=>c.dataset.v45Cell===V45.cellKey)){V45.sectionId=s.id;V45.cellKey=cells[0]?.dataset.v45Cell||null}q('v45CellStatus').textContent=V45.cellKey?`Selected cell: ${cells.findIndex(c=>c.dataset.v45Cell===V45.cellKey)+1} / ${cells.length}`:'Select a cell';q('v45ColsD').value=r.dataset.v45ColsD||Math.min(cells.length,4);q('v45ColsT').value=r.dataset.v45ColsT||Math.min(cells.length,2);q('v45ColsM').value=r.dataset.v45ColsM||1;q('v45Gap').value=r.dataset.v45Gap||parseFloat(r.style.getPropertyValue('--v45-gap'))||20;q('v45Ratio').value=r.dataset.v45Ratio||'equal';renderStructurePicker(cells.length)}if(s?.type==='navbar'){normalizeNav(s);q('v45NavAlign').value=s.style.navLinksAlign;q('v45NavGap').value=s.style.navGap;q('v45TogglePos').value=s.style.navMobileToggle;q('v45PanelPos').value=s.style.navMobilePanel;q('v45MobileCta').value=s.style.navMobileCta;q('v45MenuBg').value=s.style.navMenuBg;q('v45MenuColor').value=s.style.navMenuColor}if(s?.type==='pricing'){normalizePricing(s);const count=box(s).querySelectorAll('.pricing-card').length;q('v45PriceFeatured').innerHTML='<option value="0">None</option>'+Array.from({length:count},(_,i)=>`<option value="${i+1}">Card ${i+1}</option>`).join('');q('v45PriceBorder').value=s.style.priceBorder;q('v45PriceRadius').value=s.style.priceRadius;q('v45PriceBorderColor').value=s.style.priceBorderColor;q('v45PriceFeatured').value=String(s.style.priceFeatured||0);q('v45FeatureBorder').value=s.style.priceFeatureBorder;q('v45FeatureColor').value=s.style.priceFeatureColor;q('v45FeatureBg').value=s.style.priceFeatureBg}}
function decorateCanvas(){canvas.querySelectorAll('.v45-editor-add').forEach(x=>x.remove());canvas.querySelectorAll('.v45-cell').forEach(c=>{const sec=c.closest('.site-section'),sid=sec?.dataset.id,key=c.dataset.v45Cell;c.classList.toggle('v45-cell-selected',sid===V45.sectionId&&key===V45.cellKey);c.dataset.v45Empty=c.querySelector('.v45-element')?'0':'1';const add=document.createElement('button');add.type='button';add.className='v45-editor-add';add.textContent='+';add.title='Add element to this cell';add.onclick=e=>{e.preventDefault();e.stopPropagation();state.selected=sid;V45.sectionId=sid;V45.cellKey=key;renderSelectionOnly();updateInspector45();q('v45LayoutInspector')?.scrollIntoView({block:'nearest'})};c.appendChild(add);c.querySelectorAll('.v45-element').forEach(el=>el.draggable=true)});bindCanvas45()}
function bindCanvas45(){if(canvas.dataset.v45Bound==='1')return;canvas.dataset.v45Bound='1';canvas.addEventListener('click',e=>{const c=e.target.closest('.v45-cell');if(!c||!canvas.contains(c))return;const sec=c.closest('.site-section');if(!sec)return;state.selected=sec.dataset.id;V45.sectionId=sec.dataset.id;V45.cellKey=c.dataset.v45Cell;setTimeout(()=>{decorateCanvas();updateInspector45()},0)},true);canvas.addEventListener('dragstart',e=>{const el=e.target.closest('.v45-element');if(!el)return;const sec=el.closest('.site-section');if(!sec)return;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('application/x-v45',`${sec.dataset.id}|${el.dataset.v45Id}`);e.dataTransfer.setData('text/plain',el.dataset.v45Id);el.classList.add('v45-dragging')},true);canvas.addEventListener('dragend',()=>clearDrop(),true);canvas.addEventListener('dragover',e=>{const c=e.target.closest('.v45-cell');if(!c)return;const raw=e.dataTransfer.getData('application/x-v45')||'';if(!raw)return;e.preventDefault();clearDrop();c.classList.add('v45-drop');const t=e.target.closest('.v45-element');if(t&&!t.classList.contains('v45-dragging')){const r=t.getBoundingClientRect();t.classList.add(e.clientY<r.top+r.height/2?'v45-before':'v45-after')}},true);canvas.addEventListener('drop',e=>{const c=e.target.closest('.v45-cell');if(!c)return;const raw=e.dataTransfer.getData('application/x-v45')||'';if(!raw)return;e.preventDefault();e.stopPropagation();const [sid,id]=raw.split('|'),target=e.target.closest('.v45-element'),before=!!target?.classList.contains('v45-before');moveElement(sid,id,c.dataset.v45Cell,target?.dataset.v45Id||null,before);clearDrop()},true)}
function clearDrop(){canvas.querySelectorAll('.v45-drop,.v45-before,.v45-after,.v45-dragging').forEach(n=>n.classList.remove('v45-drop','v45-before','v45-after','v45-dragging'))}
function moveElement(sid,id,cellKey,targetId,before){const s=findSection(sid);if(!isLayout(s))return;const b=box(s),src=b.querySelector(`[data-v45-id="${CSS.escape(id)}"]`),cell=b.querySelector(`.v45-cell[data-v45-cell="${CSS.escape(cellKey)}"]`);if(!src||!cell)return;const target=targetId?b.querySelector(`[data-v45-id="${CSS.escape(targetId)}"]`):null;if(target===src)return;snapshot();if(target&&target.parentElement===cell)cell.insertBefore(src,before?target:target.nextSibling);else cell.appendChild(src);s.html=b.innerHTML;state.selected=s.id;V45.sectionId=s.id;V45.cellKey=cellKey;commit();renderCanvas()}
const publicCss=`.v45-layout{display:grid;grid-template-columns:var(--v45-template,repeat(var(--v45-cols-d,1),minmax(0,1fr)));gap:var(--v45-gap,20px);align-items:stretch}.v45-cell{min-width:0;display:flex;flex-direction:column;gap:14px}.v45-nav .nav-links{flex:1;display:flex;gap:var(--v45-nav-gap,20px);justify-content:var(--v45-links-align,center);align-items:center}.pricing-card{border:var(--v45-price-border,1px) solid var(--v45-price-border-color,#dfe3ec)!important;border-radius:var(--v45-price-radius,16px)!important;outline:none!important}.pricing-card.v45-featured{border:var(--v45-feature-border,2px) solid var(--v45-feature-color,#705cff)!important;background:var(--v45-feature-bg,#fff)!important}@media(max-width:1180px){.v45-layout{grid-template-columns:repeat(var(--v45-cols-t,var(--v45-cols-d,1)),minmax(0,1fr))}}@media(max-width:760px){.v45-layout{grid-template-columns:repeat(var(--v45-cols-m,1),minmax(0,1fr))!important}.v45-nav{position:relative!important;display:flex!important;align-items:center!important;flex-wrap:nowrap!important;gap:12px!important}.v45-nav .nav-toggle{display:inline-flex!important}.v45-nav .web-btn.v45-mobile-cta-hide{display:none!important}.v45-nav.v45-toggle-right .nav-toggle{margin-left:auto}.v45-nav.v45-toggle-left .nav-toggle{order:-1}.v45-nav.v45-toggle-center .nav-toggle{position:absolute;left:50%;transform:translateX(-50%)}.v45-nav .nav-links,.v45-nav.nav-desktop-dropdown .nav-links{display:none!important;position:absolute!important;top:calc(100% + 10px)!important;z-index:40!important;width:min(280px,calc(100vw - 32px))!important;padding:14px!important;flex-direction:column!important;background:var(--v45-menu-bg,#fff)!important;color:var(--v45-menu-color,#111827)!important;border:1px solid #e0e4ec!important;border-radius:12px!important;box-shadow:0 18px 50px rgba(15,23,42,.18)!important}.v45-nav.nav-open .nav-links{display:flex!important}.v45-nav.v45-panel-right .nav-links{right:0!important;left:auto!important;transform:none!important}.v45-nav.v45-panel-left .nav-links{left:0!important;right:auto!important;transform:none!important}.v45-nav.v45-panel-center .nav-links{left:50%!important;right:auto!important;transform:translateX(-50%)!important}.v45-nav.v45-panel-full .nav-links{left:0!important;right:0!important;width:100%!important;transform:none!important}}`;
const prevRender=renderCanvas;renderCanvas=()=>{normalizeAll();prevRender();setTimeout(()=>{decorateCanvas();updateInspector45()},0)};
const prevInspector=updateInspector;updateInspector=()=>{prevInspector();updateInspector45()};
const prevLibrary=renderLibrary;renderLibrary=()=>{prevLibrary()};
const prevClean=cleanSectionHtml;cleanSectionHtml=s=>{normalizeNav(s);normalizePricing(s);normalizeLayout(s);const b=document.createElement('div');b.innerHTML=prevClean(s);b.querySelectorAll('.v45-editor-add').forEach(x=>x.remove());b.querySelectorAll('.v45-cell-selected,.v45-drop,.v45-before,.v45-after,.v45-dragging').forEach(x=>x.classList.remove('v45-cell-selected','v45-drop','v45-before','v45-after','v45-dragging'));b.querySelectorAll('.v45-element').forEach(x=>x.removeAttribute('draggable'));return b.innerHTML};
const prevExport=exportedDocument;exportedDocument=page=>{page.sections.forEach(s=>{normalizeNav(s);normalizePricing(s);normalizeLayout(s)});return prevExport(page).replace('</head>',`<style id="v45-public">${publicCss}</style></head>`)};
normalizeAll();setTimeout(()=>{installInspector();decorateCanvas();updateInspector45();renderLibrary()},0);
})();
