(()=>{
'use strict';
const V4={sectionId:null,path:null,device:'desktop'};
const fonts=['Inter, Arial, sans-serif','system-ui, sans-serif','Arial, sans-serif','Helvetica, Arial, sans-serif','Georgia, serif','Times New Roman, serif','Verdana, sans-serif','Trebuchet MS, sans-serif','Courier New, monospace'];
const q=id=>document.getElementById(id);
const esc=v=>escapeHtml(String(v??''));
function clamp(v,a,b,d){v=Number(v);return Number.isFinite(v)?Math.max(a,Math.min(b,v)):d}
function sectionForSelection(){return findSection(V4.sectionId||state.selected)}
function boxFor(section){const b=document.createElement('div');b.innerHTML=section?.html||'';return b}
function pathOf(node,root){const p=[];let n=node;while(n&&n!==root){const par=n.parentElement;if(!par)return null;p.unshift([...par.children].indexOf(n));n=par}return n===root?p:null}
function byPath(root,path){let n=root;for(const i of path||[]){n=n?.children?.[i];if(!n)return null}return n}
function canvasNode(){const sec=document.querySelector(`.site-section[data-id="${CSS.escape(V4.sectionId||'')}"]`);if(!sec)return null;return byPath(sec.querySelector('.section-content'),V4.path)}
function storedNode(section=sectionForSelection()){if(!section||!V4.path)return null;return byPath(boxFor(section),V4.path)}
function tagLabel(n){if(!n)return 'Block';if(n.classList?.contains('faq-item'))return 'FAQ item';if(n.classList?.contains('feature-card'))return 'Feature';if(n.classList?.contains('image-text-card'))return 'Card';if(n.classList?.contains('stat-card'))return 'Stat';if(n.classList?.contains('custom-item'))return `Custom: ${n.dataset.customType||'item'}`;if(n.matches?.('.editable-image'))return 'Image';if(/^H[1-6]$/.test(n.tagName))return n.tagName;if(n.tagName==='P')return 'Paragraph';if(n.tagName==='A')return 'Link / Button';return n.tagName||'Element'}
function mutateSelected(fn,{render=true}={}){const section=sectionForSelection();if(!section||!V4.path)return;const b=boxFor(section),node=byPath(b,V4.path);if(!node)return;snapshot();fn(node,b,section);section.html=b.innerHTML;commit();if(render)renderCanvas();else updateV4Inspector()}
function deviceKey(base){return `${base}-${V4.device==='desktop'?'d':V4.device==='tablet'?'t':'m'}`}
function styleVar(node,name){return node?.style?.getPropertyValue(name)?.trim()||''}
function setResponsiveVar(node,base,value,unit=''){node.dataset.v4Responsive='1';const key=`--v4-${deviceKey(base)}`;if(value===''||value==null)node.style.removeProperty(key);else node.style.setProperty(key,`${value}${unit}`)}
function closestCustomItem(n){return n?.closest?.('.custom-item')||n}
function theme(){if(!state.project)return{bodyFont:fonts[0],headingFont:fonts[0],bodySize:18,primary:'#705cff',buttonRadius:9};state.project.theme||={};return Object.assign({bodyFont:fonts[0],headingFont:fonts[0],bodySize:18,primary:'#705cff',buttonRadius:9},state.project.theme)}
function themeCss(scope=''){const t=theme(),s=scope?`${scope} `:'';return `${s}.section-content{font-family:${t.bodyFont}}${s}.section-content h1,${s}.section-content h2,${s}.section-content h3,${s}.logo-text{font-family:${t.headingFont}}${s}.section-content p{--v4-body-size:${Number(t.bodySize)||18}px}${s}.web-btn{background:${t.primary};border-radius:${Number(t.buttonRadius)||9}px}`}
function responsiveCss(){return `[data-v4-responsive]{font-size:var(--v4-fs-d,inherit);width:var(--v4-w-d,auto);max-width:100%}.custom-stack.v4-row-layout{display:flex!important;flex-direction:row!important;flex-wrap:var(--v4-wrap,wrap);align-items:var(--v4-align,stretch);justify-content:var(--v4-justify,flex-start);gap:var(--v4-gap,18px)}.custom-stack.v4-column-layout{display:flex!important;flex-direction:column!important;gap:var(--v4-gap,18px)}.custom-stack.v4-grid-layout{display:grid!important;grid-template-columns:repeat(var(--v4-cols,2),minmax(0,1fr))!important;gap:var(--v4-gap,18px)}.custom-stack>.custom-item{min-width:0;flex:0 1 var(--v4-item-w,auto)}.v4-hidden-desktop{display:none!important}.v4-menu-items{display:flex;gap:20px;flex-wrap:wrap}.v4-menu-items a{color:inherit;text-decoration:none}@media(max-width:1180px){[data-v4-responsive]{font-size:var(--v4-fs-t,var(--v4-fs-d,inherit));width:var(--v4-w-t,var(--v4-w-d,auto))}.v4-hidden-tablet{display:none!important}}@media(max-width:760px){[data-v4-responsive]{font-size:var(--v4-fs-m,var(--v4-fs-t,var(--v4-fs-d,inherit)));width:var(--v4-w-m,var(--v4-w-t,var(--v4-w-d,auto)))}.v4-hidden-mobile{display:none!important}.custom-stack.v4-row-layout{flex-direction:column!important}.custom-stack.v4-grid-layout{grid-template-columns:1fr!important}.v4-menu-items{width:100%;flex-direction:column}}`}
function applyTheme(){if(!state.project)return;let st=q('v4ThemeStyle');if(!st){st=document.createElement('style');st.id='v4ThemeStyle';document.head.appendChild(st)}st.textContent=themeCss('#canvas');const t=theme();canvas?.style.setProperty('--v4-body-font',t.bodyFont);canvas?.style.setProperty('--v4-heading-font',t.headingFont);canvas?.style.setProperty('--v4-primary',t.primary);canvas?.style.setProperty('--v4-body-size',`${t.bodySize}px`)}
function anchorFor(section){return section?.style?.anchorId||`section-${String(section?.id||'').split('-').pop()}`}
function sanitizeAnchor(v){return String(v||'').trim().toLowerCase().replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,64)}
function linkHref(node){const type=node?.dataset?.v4LinkType||'none',val=node?.dataset?.v4LinkValue||'';if(type==='page'){const p=state.project?.pages?.find(x=>x.id===val);return p?pageFile(p):'#'}if(type==='section')return val?`#${val}`:'#';if(type==='url')return val||'#';if(type==='email')return val?`mailto:${val.replace(/^mailto:/,'')}`:'#';if(type==='phone')return val?`tel:${val.replace(/^tel:/,'')}`:'#';return '#'}
function installUI(){const form=q('inspector');if(!form||q('v4ElementInspector'))return;const element=document.createElement('fieldset');element.id='v4ElementInspector';element.className='v4-section hidden';element.innerHTML=`<legend>Element</legend><div id="v4TargetName" class="v4-target-name">Select an element inside the block</div><label><span class="v4-device-label">Font size <b id="v4DeviceBadge" class="v4-device-badge">Desktop</b></span><input id="v4FontSize" type="number" min="8" max="240" step="1" placeholder="inherit"></label><div class="v4-grid-2"><label>Font family<select id="v4FontFamily"></select></label><label>Weight<select id="v4FontWeight"><option value="">Inherit</option><option>300</option><option>400</option><option>500</option><option>600</option><option>700</option><option>800</option><option>900</option></select></label></div><div class="v4-grid-3"><label>Line height<input id="v4LineHeight" type="number" min="0.7" max="3" step="0.05" placeholder="inherit"></label><label>Letter px<input id="v4Letter" type="number" min="-10" max="30" step="0.1" placeholder="0"></label><label>Align<select id="v4ElementAlign"><option value="">Inherit</option><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></label></div><div class="v4-grid-2"><label>Transform<select id="v4Transform"><option value="">Normal</option><option value="uppercase">UPPERCASE</option><option value="lowercase">lowercase</option><option value="capitalize">Capitalize</option></select></label><label>Color<input id="v4ElementColor" type="text" placeholder="inherit"></label></div><div class="v4-grid-2"><label>Width % <span id="v4WidthDevice"></span><input id="v4ElementWidth" type="number" min="1" max="100" step="1" placeholder="auto"></label><label>Height px<input id="v4ElementHeight" type="number" min="0" max="2000" step="1" placeholder="auto"></label></div><div id="v4ImageExtra" class="v4-grid-2 hidden"><label>Image fit<select id="v4ObjectFit"><option value="cover">Cover</option><option value="contain">Contain</option><option value="fill">Fill</option></select></label><label>Radius px<input id="v4ImageRadius" type="number" min="0" max="300"></label></div><div class="v4-grid-3"><label class="check-row"><input id="v4HideDesktop" type="checkbox"><span>Hide desktop</span></label><label class="check-row"><input id="v4HideTablet" type="checkbox"><span>Hide tablet</span></label><label class="check-row"><input id="v4HideMobile" type="checkbox"><span>Hide mobile</span></label></div></fieldset>`;
const link=document.createElement('fieldset');link.id='v4LinkInspector';link.className='v4-section hidden';link.innerHTML=`<legend>Link / Action</legend><label>Action<select id="v4LinkType"><option value="none">None</option><option value="page">Project page</option><option value="section">Section / anchor</option><option value="url">External URL</option><option value="email">Email</option><option value="phone">Phone</option></select></label><label id="v4PageRow" class="hidden">Page<select id="v4LinkPage"></select></label><label id="v4SectionRow" class="hidden">Section<select id="v4LinkSection"></select></label><label id="v4ValueRow" class="hidden">Value<input id="v4LinkValue" type="text" placeholder="https://..."></label><label class="check-row"><input id="v4NewTab" type="checkbox"><span>Open in new tab</span></label><small class="v4-hint">Works for buttons, text, headings, images and cards. Page links stay connected by page ID.</small></fieldset>`;
const block=document.createElement('fieldset');block.id='v4BlockSpecific';block.className='v4-section';block.innerHTML=`<legend>Block settings</legend><label>Section anchor / ID<input id="v4SectionAnchor" type="text" placeholder="contact"></label><div id="v4CustomLayout" class="v4-custom-layout hidden"><div class="v4-grid-2"><label>Layout<select id="v4CustomMode"><option value="column">Column</option><option value="row">Row</option><option value="grid">Grid</option></select></label><label>Gap px<input id="v4CustomGap" type="number" min="0" max="200"></label></div><div class="v4-grid-2"><label>Grid columns<input id="v4CustomCols" type="number" min="1" max="12"></label><label>Wrap<select id="v4CustomWrap"><option value="wrap">Wrap</option><option value="nowrap">No wrap</option></select></label></div><div class="v4-grid-2"><label>Vertical align<select id="v4CustomAlign"><option value="stretch">Stretch</option><option value="flex-start">Top</option><option value="center">Center</option><option value="flex-end">Bottom</option></select></label><label>Horizontal<select id="v4CustomJustify"><option value="flex-start">Start</option><option value="center">Center</option><option value="space-between">Space between</option><option value="flex-end">End</option></select></label></div><small class="v4-hint">Row lets you put image + text beside each other. Select either element and set Width % above.</small></div></fieldset>`;
const actions=form.querySelector('.inspector-actions');form.insertBefore(block,actions);form.insertBefore(element,actions);form.insertBefore(link,actions);
q('v4FontFamily').innerHTML='<option value="">Inherit</option>'+fonts.map(f=>`<option value="${esc(f)}">${esc(f.split(',')[0])}</option>`).join('');
const tabBox=q('inspectorTabs');tabBox.classList.add('v4-tabs');const siteBtn=document.createElement('button');siteBtn.dataset.inspector='site';siteBtn.textContent='Site';tabBox.appendChild(siteBtn);const side=document.querySelector('.right-sidebar');const projectTools=side.querySelector('.project-tools');const site=document.createElement('form');site.id='siteInspectorPanel';site.className='inspector hidden';site.onsubmit=()=>false;site.innerHTML=`<fieldset class="v4-section"><legend>Global theme</legend><label>Heading font<select id="v4SiteHeadingFont"></select></label><label>Body font<select id="v4SiteBodyFont"></select></label><div class="v4-grid-2"><label>Body size px<input id="v4SiteBodySize" type="number" min="10" max="40"></label><label>Button radius px<input id="v4SiteButtonRadius" type="number" min="0" max="80"></label></div><label>Primary color<input id="v4SitePrimary" type="color"></label><small class="v4-hint">These are inherited by the whole site. Individual elements can override them.</small></fieldset>`;side.insertBefore(site,projectTools);
const fontOptions=fonts.map(f=>`<option value="${esc(f)}">${esc(f.split(',')[0])}</option>`).join('');q('v4SiteHeadingFont').innerHTML=fontOptions;q('v4SiteBodyFont').innerHTML=fontOptions;
bindUI();
}
function bindUI(){
  const mutateStyle=(id,fn,event='change')=>{q(id).addEventListener(event,e=>mutateSelected(n=>fn(n,e.target.value,e.target)))};
  mutateStyle('v4FontFamily',(n,v)=>n.style.fontFamily=v);
  mutateStyle('v4FontWeight',(n,v)=>n.style.fontWeight=v);
  mutateStyle('v4LineHeight',(n,v)=>n.style.lineHeight=v);
  mutateStyle('v4Letter',(n,v)=>n.style.letterSpacing=v===''?'':`${v}px`);
  mutateStyle('v4ElementAlign',(n,v)=>n.style.textAlign=v);
  mutateStyle('v4Transform',(n,v)=>n.style.textTransform=v);
  mutateStyle('v4ElementColor',(n,v)=>n.style.color=v);
  q('v4FontSize').onchange=e=>mutateSelected(n=>setResponsiveVar(n,'fs',e.target.value,'px'));
  q('v4ElementWidth').onchange=e=>mutateSelected(n=>{const target=closestCustomItem(n);setResponsiveVar(target,'w',e.target.value,'%');if(target.classList?.contains('custom-item')&&V4.device==='desktop')target.style.setProperty('--v4-item-w',e.target.value?`${e.target.value}%`:'auto')});
  q('v4ElementHeight').onchange=e=>mutateSelected(n=>{if(e.target.value==='')n.style.removeProperty('height');else n.style.height=`${e.target.value}px`});
  q('v4ObjectFit').onchange=e=>mutateSelected(n=>{const img=n.matches('.editable-image')?n:n.querySelector('.editable-image');if(img)img.style.objectFit=e.target.value});
  q('v4ImageRadius').onchange=e=>mutateSelected(n=>{const img=n.matches('.editable-image')?n:n.querySelector('.editable-image');if(img)img.style.borderRadius=`${clamp(e.target.value,0,300,0)}px`});
  [['v4HideDesktop','v4-hidden-desktop'],['v4HideTablet','v4-hidden-tablet'],['v4HideMobile','v4-hidden-mobile']].forEach(([id,cls])=>q(id).onchange=e=>mutateSelected(n=>n.classList.toggle(cls,e.target.checked)));
  q('v4LinkType').onchange=e=>mutateSelected(n=>{n.dataset.v4LinkType=e.target.value;if(e.target.value==='none'){delete n.dataset.v4LinkValue;delete n.dataset.v4NewTab}});
  q('v4LinkPage').onchange=e=>mutateSelected(n=>{n.dataset.v4LinkType='page';n.dataset.v4LinkValue=e.target.value});
  q('v4LinkSection').onchange=e=>mutateSelected(n=>{n.dataset.v4LinkType='section';n.dataset.v4LinkValue=e.target.value});
  q('v4LinkValue').onchange=e=>mutateSelected(n=>n.dataset.v4LinkValue=e.target.value);
  q('v4NewTab').onchange=e=>mutateSelected(n=>n.dataset.v4NewTab=e.target.checked?'1':'');
  q('v4SectionAnchor').onchange=e=>{const s=sectionForSelection();if(!s)return;snapshot();s.style.anchorId=sanitizeAnchor(e.target.value);commit();renderCanvas()};
  [['v4CustomMode','mode'],['v4CustomGap','gap'],['v4CustomCols','cols'],['v4CustomWrap','wrap'],['v4CustomAlign','align'],['v4CustomJustify','justify']].forEach(([id,key])=>q(id).onchange=e=>setCustomLayout(key,e.target.value));
  const setTheme=(key,value)=>{if(!state.project)return;snapshot();state.project.theme=theme();state.project.theme[key]=value;commit();applyTheme();updateSiteInspector()};
  q('v4SiteHeadingFont').onchange=e=>setTheme('headingFont',e.target.value);q('v4SiteBodyFont').onchange=e=>setTheme('bodyFont',e.target.value);q('v4SiteBodySize').onchange=e=>setTheme('bodySize',clamp(e.target.value,10,40,18));q('v4SiteButtonRadius').onchange=e=>setTheme('buttonRadius',clamp(e.target.value,0,80,9));q('v4SitePrimary').oninput=debounce(e=>setTheme('primary',e.target.value),250);
  canvas.addEventListener('click',selectElement,true);
  document.addEventListener('click',e=>{const d=e.target.closest('[data-device]')?.dataset.device;if(d){V4.device=d;setTimeout(updateV4Inspector,0)}},true);
}
function selectElement(e){const sec=e.target.closest('.site-section');if(!sec||e.target.closest('.section-toolbar')||e.target.closest('.auto-page-nav'))return;const root=sec.querySelector('.section-content');const target=e.target.closest('[contenteditable=true],.editable-image,.web-btn,.faq-item,.feature-card,.image-text-card,.stat-card,.custom-item');if(!target||!root.contains(target))return;if(target.tagName==='A')e.preventDefault();V4.sectionId=sec.dataset.id;V4.path=pathOf(target,root);state.selected=V4.sectionId;decorateCanvas();updateV4Inspector()}
function decorateCanvas(){if(!canvas)return;canvas.querySelectorAll('.v4-selected-element').forEach(n=>n.classList.remove('v4-selected-element'));canvas.querySelectorAll('[contenteditable=true],.editable-image,.web-btn,.faq-item,.feature-card,.image-text-card,.stat-card,.custom-item').forEach(n=>{if(!n.closest('.auto-page-nav'))n.classList.add('v4-selectable')});const n=canvasNode();if(n)n.classList.add('v4-selected-element');applyTheme()}
function canLink(n){return !!n&&n.matches('a,button,img,h1,h2,h3,h4,h5,h6,p,article,.custom-item,.feature-card,.image-text-card,.stat-card')}
function updateV4Inspector(){if(!q('v4ElementInspector'))return;const s=sectionForSelection();if(!s){q('v4ElementInspector').classList.add('hidden');q('v4LinkInspector').classList.add('hidden');return}q('v4SectionAnchor').value=s.style?.anchorId||'';const custom=s.type==='custom';q('v4CustomLayout').classList.toggle('hidden',!custom);if(custom)readCustomLayout(s);const n=storedNode(s);q('v4ElementInspector').classList.toggle('hidden',!n);if(!n){q('v4LinkInspector').classList.add('hidden');return}q('v4TargetName').textContent=tagLabel(n);q('v4DeviceBadge').textContent=V4.device;q('v4WidthDevice').textContent=`(${V4.device})`;q('v4FontFamily').value=n.style.fontFamily||'';q('v4FontWeight').value=n.style.fontWeight||'';q('v4LineHeight').value=n.style.lineHeight||'';q('v4Letter').value=parseFloat(n.style.letterSpacing)||'';q('v4ElementAlign').value=n.style.textAlign||'';q('v4Transform').value=n.style.textTransform||'';q('v4ElementColor').value=n.style.color||'';q('v4FontSize').value=parseFloat(styleVar(n,`--v4-${deviceKey('fs')}`))||'';const widthTarget=closestCustomItem(n);q('v4ElementWidth').value=parseFloat(styleVar(widthTarget,`--v4-${deviceKey('w')}`))||parseFloat(styleVar(widthTarget,'--v4-item-w'))||'';q('v4ElementHeight').value=parseFloat(n.style.height)||'';q('v4HideDesktop').checked=n.classList.contains('v4-hidden-desktop');q('v4HideTablet').checked=n.classList.contains('v4-hidden-tablet');q('v4HideMobile').checked=n.classList.contains('v4-hidden-mobile');const img=n.matches('.editable-image')?n:n.querySelector('.editable-image');q('v4ImageExtra').classList.toggle('hidden',!img);if(img){q('v4ObjectFit').value=img.style.objectFit||'cover';q('v4ImageRadius').value=parseFloat(img.style.borderRadius)||''}q('v4LinkInspector').classList.toggle('hidden',!canLink(n));if(canLink(n))updateLinkInspector(n)}
function updateLinkInspector(n){const type=n.dataset.v4LinkType||'none';q('v4LinkType').value=type;q('v4PageRow').classList.toggle('hidden',type!=='page');q('v4SectionRow').classList.toggle('hidden',type!=='section');q('v4ValueRow').classList.toggle('hidden',!['url','email','phone'].includes(type));q('v4LinkPage').innerHTML=(state.project?.pages||[]).map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');q('v4LinkSection').innerHTML=currentSections().map(s=>`<option value="${esc(anchorFor(s))}">${esc(blockName(s.type))} · #${esc(anchorFor(s))}</option>`).join('');if(type==='page')q('v4LinkPage').value=n.dataset.v4LinkValue||'';if(type==='section')q('v4LinkSection').value=n.dataset.v4LinkValue||'';q('v4LinkValue').value=['url','email','phone'].includes(type)?n.dataset.v4LinkValue||'':'';q('v4NewTab').checked=n.dataset.v4NewTab==='1'}
function setCustomLayout(key,val){const s=sectionForSelection();if(!s||s.type!=='custom')return;const b=boxFor(s),stack=b.querySelector('.custom-stack');if(!stack)return;snapshot();if(key==='mode'){stack.classList.remove('v4-row-layout','v4-column-layout','v4-grid-layout');stack.classList.add(`v4-${val}-layout`);stack.dataset.v4Mode=val}else if(key==='gap'){stack.style.setProperty('--v4-gap',`${clamp(val,0,200,18)}px`);stack.dataset.v4Gap=String(clamp(val,0,200,18))}else if(key==='cols'){stack.style.setProperty('--v4-cols',String(clamp(val,1,12,2)));stack.dataset.v4Cols=String(clamp(val,1,12,2))}else if(key==='wrap'){stack.style.setProperty('--v4-wrap',val);stack.dataset.v4Wrap=val}else if(key==='align'){stack.style.setProperty('--v4-align',val);stack.dataset.v4Align=val}else if(key==='justify'){stack.style.setProperty('--v4-justify',val);stack.dataset.v4Justify=val}s.html=b.innerHTML;commit();renderCanvas()}
function readCustomLayout(s){const b=boxFor(s),stack=b.querySelector('.custom-stack');if(!stack)return;const mode=stack.dataset.v4Mode|| (stack.classList.contains('v4-row-layout')?'row':stack.classList.contains('v4-grid-layout')?'grid':'column');q('v4CustomMode').value=mode;q('v4CustomGap').value=stack.dataset.v4Gap||parseFloat(styleVar(stack,'--v4-gap'))||18;q('v4CustomCols').value=stack.dataset.v4Cols||parseFloat(styleVar(stack,'--v4-cols'))||2;q('v4CustomWrap').value=stack.dataset.v4Wrap||'wrap';q('v4CustomAlign').value=stack.dataset.v4Align||'stretch';q('v4CustomJustify').value=stack.dataset.v4Justify||'flex-start'}
function updateSiteInspector(){if(!q('v4SiteHeadingFont')||!state.project)return;const t=theme();q('v4SiteHeadingFont').value=t.headingFont;q('v4SiteBodyFont').value=t.bodyFont;q('v4SiteBodySize').value=t.bodySize;q('v4SiteButtonRadius').value=t.buttonRadius;q('v4SitePrimary').value=/^#[0-9a-f]{6}$/i.test(t.primary)?t.primary:'#705cff'}
const prevRenderCanvas=renderCanvas;renderCanvas=()=>{prevRenderCanvas();decorateCanvas()};
const prevUpdateInspector=updateInspector;updateInspector=()=>{prevUpdateInspector();updateV4Inspector()};
const prevSetInspectorTab=setInspectorTab;setInspectorTab=name=>{prevSetInspectorTab(name);q('siteInspectorPanel')?.classList.toggle('hidden',name!=='site');if(name==='site')updateSiteInspector()};
const prevClean=cleanSectionHtml;cleanSectionHtml=section=>{const b=document.createElement('div');b.innerHTML=prevClean(section);b.querySelectorAll('.v4-selected-element,.v4-selectable').forEach(n=>n.classList.remove('v4-selected-element','v4-selectable'));const anchor=anchorFor(section);if(anchor){const m=document.createElement('span');m.id=anchor;m.className='v4-anchor-marker';b.prepend(m)}b.querySelectorAll('[data-v4-link-type]').forEach(n=>{const type=n.dataset.v4LinkType;if(!type||type==='none')return;const href=linkHref(n),target=n.dataset.v4NewTab==='1'?'_blank':'';if(n.tagName==='A'){n.href=href;if(target)n.target=target}else if(n.tagName==='BUTTON'){const a=document.createElement('a');[...n.attributes].forEach(a0=>{if(a0.name!=='type')a.setAttribute(a0.name,a0.value)});a.className=n.className;a.innerHTML=n.innerHTML;a.href=href;if(target)a.target=target;n.replaceWith(a)}else{const a=document.createElement('a');a.href=href;a.className='v4-export-link';if(target)a.target=target;n.replaceWith(a);a.appendChild(n)}});return b.innerHTML};
const prevExport=exportedDocument;exportedDocument=page=>{const html=prevExport(page),css=themeCss('')+responsiveCss();return html.replace('</head>',`<style id="v4-export-styles">${css}</style></head>`)};
installUI();
setTimeout(()=>{applyTheme();decorateCanvas();updateSiteInspector();updateV4Inspector()},0);
})();
