(()=>{
'use strict';
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const I18N={
 ru:{elements:'Элементы',find:'Найти элемент',hint:'Выберите Container/ячейку и добавьте элемент. Если контейнер не выбран, будет создан новый.',heading:'Заголовок',text:'Текст',image:'Изображение',button:'Кнопка',divider:'Разделитель',spacer:'Отступ',element:'Элемент',select:'Выберите элемент на холсте',content:'Контент элемента',alt:'ALT описание',upload:'Загрузить изображение',duplicate:'Дублировать элемент',remove:'Удалить элемент'},
 az:{elements:'Elementlər',find:'Element axtar',hint:'Container/xana seçin və element əlavə edin. Heç nə seçilməyibsə yeni container yaradılacaq.',heading:'Başlıq',text:'Mətn',image:'Şəkil',button:'Düymə',divider:'Ayırıcı',spacer:'Boşluq',element:'Element',select:'Sahədə element seçin',content:'Element məzmunu',alt:'ALT təsviri',upload:'Şəkil yüklə',duplicate:'Elementi kopyala',remove:'Elementi sil'},
 en:{elements:'Elements',find:'Find element',hint:'Select a Container/cell and add an element. If none is selected, a new container will be created.',heading:'Heading',text:'Text',image:'Image',button:'Button',divider:'Divider',spacer:'Spacer',element:'Element',select:'Select an element on canvas',content:'Element content',alt:'ALT description',upload:'Upload image',duplicate:'Duplicate element',remove:'Delete element'}
};
const lang=()=>document.getElementById('uiLanguage')?.value||'ru',tr=k=>I18N[lang()]?.[k]||I18N.en[k]||k;
const types=[['heading','H',()=>tr('heading')],['text','¶',()=>tr('text')],['image','▧',()=>tr('image')],['button','▣',()=>tr('button')],['divider','—',()=>tr('divider')],['spacer','↕',()=>tr('spacer')]];
function pathOf(node,root){const p=[];let n=node;while(n&&n!==root){const par=n.parentElement;if(!par)return null;p.unshift([...par.children].indexOf(n));n=par}return n===root?p:null}
function byPath(root,path){let n=root;for(const i of path||[]){n=n?.children?.[i];if(!n)return null}return n}
function htmlBox(s){const b=document.createElement('div');b.innerHTML=s?.html||'';return b}
function liveSelected(){return q('#canvas .v4-selected-element')}
function liveSection(){return liveSelected()?.closest('.site-section')||q(`#canvas .site-section[data-id="${CSS.escape(state.selected||'')}"]`)}
function selectedPath(){const n=liveSelected(),root=liveSection()?.querySelector('.section-content');return n&&root?pathOf(n,root):null}
function elementNode(type){const n=document.createElement('div');n.className='custom-item v45-element';n.dataset.customType=type;n.dataset.v45Id=uid('el');if(type==='heading')n.innerHTML='<h2 contenteditable="true">New heading</h2>';else if(type==='text')n.innerHTML='<p contenteditable="true">New text</p>';else if(type==='image')n.innerHTML=`<img class="editable-image" src="${placeholderSvg('YOUR IMAGE')}" alt="Image" data-default="true">`;else if(type==='button')n.innerHTML='<a class="web-btn" href="#" contenteditable="true">Button</a>';else if(type==='divider')n.innerHTML='<hr class="content-divider">';else if(type==='spacer')n.innerHTML='<div style="height:56px"></div>';return n}
function isLayout(s){return !!s&&/^layout(1|2|3|4|Grid)$/.test(s.type)}
function selectedCell(){const c=q('#canvas .v45-cell.v45-cell-selected');if(!c)return null;const sec=c.closest('.site-section');return sec?{sid:sec.dataset.id,key:c.dataset.v45Cell}:null}
function appendToCell(type,sid,key){const s=findSection(sid);if(!s||!isLayout(s))return false;const b=htmlBox(s),c=b.querySelector(`.v45-cell[data-v45-cell="${CSS.escape(key||'')}"]`)||b.querySelector('.v45-cell');if(!c)return false;snapshot();c.appendChild(elementNode(type));s.html=b.innerHTML;state.selected=s.id;commit();renderCanvas();setTimeout(()=>selectNewestElement(s.id,key),0);return true}
function selectNewestElement(sid,key){const c=q(`#canvas .site-section[data-id="${CSS.escape(sid)}"] .v45-cell[data-v45-cell="${CSS.escape(key||'')}"]`);const el=c?.querySelector('.v45-element:last-of-type');const target=el?.querySelector('[contenteditable=true],.editable-image,.web-btn')||el;if(target){target.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,view:window}));setInspectorTab('element')}}
function createContainerWith(type){const list=currentSections(),idx=list.findIndex(x=>x.id===state.selected),s=makeSection('layout1'),b=htmlBox(s),cell=b.querySelector('.v45-cell');if(!cell)return;snapshot();cell.appendChild(elementNode(type));s.html=b.innerHTML;list.splice(idx<0?list.length:idx+1,0,s);state.selected=s.id;commit();renderAll();setTimeout(()=>selectNewestElement(s.id,cell.dataset.v45Cell),0)}
function addElement(type){const cell=selectedCell();if(cell&&appendToCell(type,cell.sid,cell.key))return;const s=findSection(state.selected);if(isLayout(s)){const b=htmlBox(s),key=b.querySelector('.v45-cell')?.dataset.v45Cell;if(key&&appendToCell(type,s.id,key))return}createContainerWith(type)}
function installLeft(){const tabs=q('#majorTabs');if(!tabs||q('[data-panel="elements"]'))return;const pages=tabs.querySelector('[data-panel="pages"]'),btn=document.createElement('button');btn.dataset.panel='elements';btn.textContent=tr('elements');tabs.insertBefore(btn,pages);const panel=document.createElement('section');panel.id='elementsPanel';panel.className='hidden';panel.innerHTML=`<label class="search"><span>⌕</span><input id="elementSearch" type="search" placeholder="${tr('find')}"></label><div class="v46-element-list" id="v46ElementList"></div><div class="sidebar-note" id="v46ElementHint">${tr('hint')}</div>`;q('#pagesPanel').before(panel);btn.onclick=()=>setMajorPanel('elements');q('#elementSearch').oninput=renderElements;renderElements();
 const old=setMajorPanel;setMajorPanel=name=>{if(name==='elements'){qa('#majorTabs button').forEach(b=>b.classList.toggle('active',b.dataset.panel==='elements'));q('#blocksPanel')?.classList.add('hidden');q('#pagesPanel')?.classList.add('hidden');panel.classList.remove('hidden');q('#leftPanelTitle').textContent=tr('elements');return}panel.classList.add('hidden');old(name)};
}
function renderElements(){const list=q('#v46ElementList');if(!list)return;const s=(q('#elementSearch')?.value||'').toLowerCase();list.innerHTML=types.filter(([, ,label])=>label().toLowerCase().includes(s)).map(([type,icon,label])=>`<button class="v46-element-card" type="button" draggable="true" data-v46-element="${type}"><span>${icon}</span><strong>${label()}</strong><small>Drag / click</small></button>`).join('');qa('[data-v46-element]').forEach(b=>{b.onclick=()=>addElement(b.dataset.v46Element);b.ondragstart=e=>{e.dataTransfer.effectAllowed='copy';e.dataTransfer.setData('application/x-v46-element',b.dataset.v46Element);e.dataTransfer.setData('text/plain',b.dataset.v46Element)}})}
function installElementInspector(){const tabs=q('#inspectorTabs');if(!tabs||q('[data-inspector="element"]'))return;const page=tabs.querySelector('[data-inspector="page"]'),btn=document.createElement('button');btn.dataset.inspector='element';btn.textContent=tr('element');tabs.insertBefore(btn,page);const block=q('#blockInspectorPanel'),panel=document.createElement('section');panel.id='elementInspectorPanel';panel.className='inspector hidden';panel.innerHTML=`<div id="v46ElementEmpty" class="empty-inspector"><div class="empty-icon">◇</div><p>${tr('select')}</p></div><form id="v46ElementForm" class="inspector hidden" onsubmit="return false"><fieldset id="v46ElementContent" class="v4-section"><legend>${tr('content')}</legend><div id="v46ElementKind" class="v4-target-name">Element</div><div id="v46ImageContent" class="hidden"><label class="button ghost wide file-button"><span>${tr('upload')}</span><input id="v46ImageInput" type="file" accept="image/png,image/jpeg,image/webp,image/gif,image/svg+xml"></label><label>${tr('alt')}<input id="v46ImageAlt" type="text"></label></div></fieldset><div id="v46MovedControls"></div><div class="v46-element-actions"><button id="v46DuplicateElement" type="button" class="button ghost">${tr('duplicate')}</button><button id="v46DeleteElement" type="button" class="button danger">${tr('remove')}</button></div></form>`;block.after(panel);btn.onclick=()=>setInspectorTab('element');
 const holder=q('#v46MovedControls');['v4ElementInspector','v4LinkInspector','v42ElementStyle','v42Media','v42Button'].forEach(id=>{const el=document.getElementById(id);if(el)holder.appendChild(el)});q('#v46ImageInput').onchange=e=>uploadSelectedImage(e.target.files?.[0]);q('#v46ImageAlt').onchange=e=>mutateSelectedElement((n)=>{const img=n.matches?.('.editable-image')?n:n.querySelector?.('.editable-image');if(img)img.alt=e.target.value});q('#v46DuplicateElement').onclick=duplicateSelected;q('#v46DeleteElement').onclick=deleteSelected;
 const old=setInspectorTab;setInspectorTab=name=>{if(name==='element'){qa('#inspectorTabs button').forEach(b=>b.classList.toggle('active',b.dataset.inspector==='element'));q('#blockInspectorPanel')?.classList.add('hidden');q('#pageInspectorPanel')?.classList.add('hidden');q('#seoInspectorPanel')?.classList.add('hidden');q('#siteInspectorPanel')?.classList.add('hidden');panel.classList.remove('hidden');refreshElementPanel();return}panel.classList.add('hidden');old(name)};
}
function selectedStored(){const s=findSection(state.selected),path=selectedPath();if(!s||!path)return null;const b=htmlBox(s);return{section:s,box:b,node:byPath(b,path),path}}
function mutateSelectedElement(fn){const x=selectedStored();if(!x?.node)return;snapshot();fn(x.node,x.box,x.section);x.section.html=x.box.innerHTML;commit();renderCanvas();setTimeout(refreshElementPanel,0)}
function targetWrapper(n){return n?.closest?.('.v45-element')||n?.closest?.('.custom-item')||n}
function duplicateSelected(){const x=selectedStored();if(!x?.node)return;let n=targetWrapper(x.node);if(!n?.parentElement)return;snapshot();const c=n.cloneNode(true);if(c.dataset?.v45Id)c.dataset.v45Id=uid('el');n.parentElement.insertBefore(c,n.nextSibling);x.section.html=x.box.innerHTML;commit();renderCanvas();setInspectorTab('block')}
function deleteSelected(){const x=selectedStored();if(!x?.node)return;let n=targetWrapper(x.node);if(!n)return;snapshot();n.remove();x.section.html=x.box.innerHTML;commit();renderCanvas();setInspectorTab('block')}
function uploadSelectedImage(file){if(!file)return;if(file.size>8*1024*1024)return notify(tr('imageTooLarge'));const reader=new FileReader();reader.onload=()=>mutateSelectedElement(n=>{const img=n.matches?.('.editable-image')?n:n.querySelector?.('.editable-image');if(img){img.src=reader.result;img.removeAttribute('data-default')}});reader.readAsDataURL(file)}
function refreshElementPanel(){const panel=q('#elementInspectorPanel');if(!panel)return;const n=liveSelected(),form=q('#v46ElementForm'),empty=q('#v46ElementEmpty');empty.classList.toggle('hidden',!!n);form.classList.toggle('hidden',!n);if(!n)return;const img=n.matches?.('.editable-image')?n:n.querySelector?.('.editable-image');q('#v46ImageContent').classList.toggle('hidden',!img);if(img)q('#v46ImageAlt').value=img.alt||'';let kind=n.tagName;if(n.matches?.('.web-btn'))kind=tr('button');else if(img)kind=tr('image');else if(/^H[1-6]$/.test(n.tagName))kind=tr('heading');else if(n.tagName==='P')kind=tr('text');q('#v46ElementKind').textContent=kind||tr('element')}
function bindCanvasAutoTabs(){q('#canvas')?.addEventListener('click',e=>{if(e.target.closest('.section-toolbar,.v45-editor-add'))return;const candidate=e.target.closest('[contenteditable=true],.editable-image,.web-btn,.faq-item,.feature-card,.image-text-card,.stat-card,.testimonial-card,.pricing-card,.custom-item,.v45-element');if(candidate){setTimeout(()=>{if(liveSelected())setInspectorTab('element')},0);return}if(e.target.closest('.site-section'))setTimeout(()=>setInspectorTab('block'),0)},true)}
function bindElementDrops(){const canvas=q('#canvas');if(!canvas||canvas.dataset.v46DropBound==='1')return;canvas.dataset.v46DropBound='1';canvas.addEventListener('dragover',e=>{const type=e.dataTransfer?.types?.includes('application/x-v46-element');const c=e.target.closest('.v45-cell');if(type&&c){e.preventDefault();e.dataTransfer.dropEffect='copy';c.classList.add('v46-element-drop')}},true);canvas.addEventListener('dragleave',e=>{e.target.closest('.v45-cell')?.classList.remove('v46-element-drop')},true);canvas.addEventListener('drop',e=>{const type=e.dataTransfer?.getData('application/x-v46-element');const c=e.target.closest('.v45-cell');if(!type||!c)return;e.preventDefault();e.stopPropagation();qa('.v46-element-drop').forEach(x=>x.classList.remove('v46-element-drop'));const sec=c.closest('.site-section');if(sec)appendToCell(type,sec.dataset.id,c.dataset.v45Cell)},true)}
function translate46(){const b=q('[data-panel="elements"]');if(b)b.textContent=tr('elements');const t=q('[data-inspector="element"]');if(t)t.textContent=tr('element');if(q('#elementSearch'))q('#elementSearch').placeholder=tr('find');if(q('#v46ElementHint'))q('#v46ElementHint').textContent=tr('hint');renderElements()}
function install(){installLeft();installElementInspector();bindCanvasAutoTabs();bindElementDrops();document.getElementById('uiLanguage')?.addEventListener('change',()=>setTimeout(translate46,0));refreshElementPanel()}
setTimeout(install,0);
})();