(()=>{
'use strict';
const q=id=>document.getElementById(id), clamp=(v,a,b,d)=>{v=Number(v);return Number.isFinite(v)?Math.max(a,Math.min(b,v)):d};
const pathOf=(node,root)=>{const p=[];let n=node;while(n&&n!==root){const par=n.parentElement;if(!par)return null;p.unshift([...par.children].indexOf(n));n=par}return n===root?p:null};
const byPath=(root,path)=>{let n=root;for(const i of path||[]){n=n?.children?.[i];if(!n)return null}return n};
const sectionEl=()=>document.querySelector(`.site-section[data-id="${CSS.escape(state.selected||'')}"]`);
const liveSelected=()=>sectionEl()?.querySelector('.v4-selected-element')||null;
const boxFor=s=>{const b=document.createElement('div');b.innerHTML=s?.html||'';return b};
function currentPath(){const sec=sectionEl(),root=sec?.querySelector('.section-content'),n=liveSelected();return root&&n?pathOf(n,root):null}
function mutatePath(path,fn,{render=true}={}){const s=findSection(state.selected);if(!s||!path)return;const b=boxFor(s),n=byPath(b,path);if(!n)return;snapshot();fn(n,b,s);s.html=b.innerHTML;commit();if(render)renderCanvas();else refresh()}
function mutateSelected(fn,opts){mutatePath(currentPath(),fn,opts)}
function label(n){if(!n)return'Element';if(n.classList.contains('v42-container'))return'Container';if(n.classList.contains('faq-item'))return'FAQ';if(n.classList.contains('feature-card'))return'Feature';if(n.classList.contains('image-text-card'))return'Card';if(n.classList.contains('stat-card'))return'Stat';if(n.classList.contains('testimonial-card'))return'Testimonial';if(n.classList.contains('pricing-card'))return'Pricing';if(n.classList.contains('custom-item'))return`Custom · ${n.dataset.customType||'item'}`;if(n.matches('.editable-image'))return'Image';if(n.matches('.web-btn'))return'Button';if(/^H[1-6]$/.test(n.tagName))return n.tagName;if(n.tagName==='P')return'Paragraph';return n.tagName}
function install(){const form=q('inspector');if(!form||q('v42ElementStyle'))return;const actions=form.querySelector('.inspector-actions');
 const style=document.createElement('fieldset');style.id='v42ElementStyle';style.className='v42-section hidden';style.innerHTML=`<legend>Element style</legend><label>Background<input id="v42Bg" type="text" placeholder="transparent / #ffffff"></label><div><div class="v42-grid-4"><span class="v42-side-label">Top</span><span class="v42-side-label">Right</span><span class="v42-side-label">Bottom</span><span class="v42-side-label">Left</span></div><div class="v42-grid-4"><input id="v42Pt" class="v42-mini-input" type="number" placeholder="P"><input id="v42Pr" class="v42-mini-input" type="number" placeholder="P"><input id="v42Pb" class="v42-mini-input" type="number" placeholder="P"><input id="v42Pl" class="v42-mini-input" type="number" placeholder="P"></div><small>Padding px</small></div><div><div class="v42-grid-4"><span class="v42-side-label">Top</span><span class="v42-side-label">Right</span><span class="v42-side-label">Bottom</span><span class="v42-side-label">Left</span></div><div class="v42-grid-4"><input id="v42Mt" class="v42-mini-input" type="number" placeholder="M"><input id="v42Mr" class="v42-mini-input" type="number" placeholder="M"><input id="v42Mb" class="v42-mini-input" type="number" placeholder="M"><input id="v42Ml" class="v42-mini-input" type="number" placeholder="M"></div><small>Margin px</small></div><div class="v42-grid-2"><label>Border px<input id="v42Border" type="number" min="0" max="30"></label><label>Border color<input id="v42BorderColor" type="text" placeholder="#dfe3ec"></label></div><div class="v42-grid-2"><label>Radius px<input id="v42Radius" type="number" min="0" max="300"></label><label>Opacity %<input id="v42Opacity" type="number" min="0" max="100"></label></div><label>Shadow<select id="v42Shadow"><option value="">None</option><option value="v42-shadow-sm">Small</option><option value="v42-shadow-md">Medium</option><option value="v42-shadow-lg">Large</option></select></label></fieldset>`;
 const media=document.createElement('fieldset');media.id='v42Media';media.className='v42-section hidden';media.innerHTML=`<legend>Image / Media</legend><div class="v42-grid-2"><label>Aspect ratio<select id="v42Ratio"><option value="">Auto</option><option value="1/1">1:1</option><option value="4/3">4:3</option><option value="3/2">3:2</option><option value="16/9">16:9</option><option value="2/3">2:3</option></select></label><label>Position<select id="v42Position"><option value="50% 50%">Center</option><option value="50% 0%">Top</option><option value="50% 100%">Bottom</option><option value="0% 50%">Left</option><option value="100% 50%">Right</option></select></label></div></fieldset>`;
 const button=document.createElement('fieldset');button.id='v42Button';button.className='v42-section hidden';button.innerHTML=`<legend>Button</legend><div class="v42-grid-2"><label>Style<select id="v42BtnVariant"><option value="filled">Filled</option><option value="outline">Outline</option><option value="text">Text</option></select></label><label>Size<select id="v42BtnSize"><option value="md">Medium</option><option value="sm">Small</option><option value="lg">Large</option></select></label></div><div class="v42-grid-2"><label>Accent color<input id="v42BtnColor" type="text" placeholder="#705cff"></label><label>Icon<input id="v42BtnIcon" type="text" maxlength="4" placeholder="→"></label></div><label>Icon position<select id="v42BtnIconPos"><option value="right">Right</option><option value="left">Left</option></select></label></fieldset>`;
 const nested=document.createElement('fieldset');nested.id='v42Nested';nested.className='v42-section hidden';nested.innerHTML=`<legend>Nested layout</legend><div class="v42-nested-tools"><div class="v42-add-row"><button type="button" data-v42-add="container">+ Container</button><button type="button" data-v42-add="heading">+ Heading</button><button type="button" data-v42-add="text">+ Text</button><button type="button" data-v42-add="image">+ Image</button><button type="button" data-v42-add="button">+ Button</button><button type="button" data-v42-add="divider">+ Divider</button></div><small>Adds to the selected Container; otherwise to the root Custom block.</small><div id="v42ContainerSettings" class="hidden"><div class="v42-grid-2"><label>Direction<select id="v42Dir"><option value="column">Column</option><option value="row">Row</option></select></label><label>Gap px<input id="v42Gap" type="number" min="0" max="200"></label></div><div class="v42-grid-2"><label>Align<select id="v42Align"><option value="stretch">Stretch</option><option value="flex-start">Start</option><option value="center">Center</option><option value="flex-end">End</option></select></label><label>Justify<select id="v42Justify"><option value="flex-start">Start</option><option value="center">Center</option><option value="space-between">Space between</option><option value="flex-end">End</option></select></label></div><label>Wrap<select id="v42Wrap"><option value="wrap">Wrap</option><option value="nowrap">No wrap</option></select></label></div></div></fieldset>`;
 const layers=document.createElement('fieldset');layers.id='v42Layers';layers.className='v42-section';layers.innerHTML=`<legend>Layers / Navigator</legend><div id="v42LayerList" class="v42-layer-list"></div><small>Drag Custom items to reorder. Drop onto a Container to move inside it.</small></fieldset>`;
 form.insertBefore(style,actions);form.insertBefore(media,actions);form.insertBefore(button,actions);form.insertBefore(nested,actions);form.insertBefore(layers,actions);
 addPreviewWidth();bind();refresh();
}
function addPreviewWidth(){const bar=document.querySelector('.device-switcher');if(!bar||q('v42Viewport'))return;const wrap=document.createElement('div');wrap.className='v42-preview-width';wrap.innerHTML='<input id="v42Viewport" type="number" min="280" max="1920" step="1" placeholder="px"><span>custom px</span>';bar.after(wrap);q('v42Viewport').onchange=e=>{const v=clamp(e.target.value,280,1920,0);if(!v)return;frame.className='canvas-frame';frame.style.width=`${v}px`;frame.style.maxWidth='none';document.querySelectorAll('[data-device]').forEach(b=>b.classList.remove('active'))};document.addEventListener('click',e=>{if(e.target.closest('[data-device]')){frame.style.width='';frame.style.maxWidth='';q('v42Viewport').value=''}},true)}
function bind(){
 const css=(id,prop,unit='')=>q(id).onchange=e=>mutateSelected(n=>{const v=e.target.value;if(v==='')n.style.removeProperty(prop);else n.style[prop]=`${v}${unit}`});
 q('v42Bg').onchange=e=>mutateSelected(n=>n.style.background=e.target.value);
 [['v42Pt','paddingTop'],['v42Pr','paddingRight'],['v42Pb','paddingBottom'],['v42Pl','paddingLeft'],['v42Mt','marginTop'],['v42Mr','marginRight'],['v42Mb','marginBottom'],['v42Ml','marginLeft']].forEach(([id,p])=>css(id,p,'px'));
 q('v42Border').onchange=e=>mutateSelected(n=>{n.style.borderStyle=Number(e.target.value)?'solid':'';n.style.borderWidth=e.target.value?`${clamp(e.target.value,0,30,0)}px`:''});
 q('v42BorderColor').onchange=e=>mutateSelected(n=>n.style.borderColor=e.target.value);css('v42Radius','borderRadius','px');q('v42Opacity').onchange=e=>mutateSelected(n=>n.style.opacity=String(clamp(e.target.value,0,100,100)/100));
 q('v42Shadow').onchange=e=>mutateSelected(n=>{n.classList.remove('v42-shadow-sm','v42-shadow-md','v42-shadow-lg');if(e.target.value)n.classList.add(e.target.value)});
 q('v42Ratio').onchange=e=>mutateSelected(n=>{const img=n.matches('.editable-image')?n:n.querySelector('.editable-image');if(!img)return;img.classList.toggle('v42-ratio',!!e.target.value);if(e.target.value)img.style.setProperty('--v42-ratio',e.target.value);else img.style.removeProperty('--v42-ratio')});
 q('v42Position').onchange=e=>mutateSelected(n=>{const img=n.matches('.editable-image')?n:n.querySelector('.editable-image');if(img)img.style.objectPosition=e.target.value});
 q('v42BtnVariant').onchange=e=>mutateSelected(n=>applyButton(n,{variant:e.target.value}));q('v42BtnSize').onchange=e=>mutateSelected(n=>applyButton(n,{size:e.target.value}));q('v42BtnColor').onchange=e=>mutateSelected(n=>applyButton(n,{color:e.target.value}));q('v42BtnIcon').onchange=e=>mutateSelected(n=>applyButton(n,{icon:e.target.value,pos:q('v42BtnIconPos').value}));q('v42BtnIconPos').onchange=e=>mutateSelected(n=>applyButton(n,{icon:q('v42BtnIcon').value,pos:e.target.value}));
 q('v42Nested').onclick=e=>{const b=e.target.closest('[data-v42-add]');if(b){e.preventDefault();addNested(b.dataset.v42Add)}};
 [['v42Dir','--v42-dir'],['v42Align','--v42-align'],['v42Justify','--v42-justify'],['v42Wrap','--v42-wrap']].forEach(([id,p])=>q(id).onchange=e=>mutateSelected(n=>{const c=n.classList.contains('v42-container')?n:n.closest?.('.v42-container');const inner=c?.querySelector(':scope>.v42-container-inner');if(inner)inner.style.setProperty(p,e.target.value)}));q('v42Gap').onchange=e=>mutateSelected(n=>{const c=n.classList.contains('v42-container')?n:n.closest?.('.v42-container');const inner=c?.querySelector(':scope>.v42-container-inner');if(inner)inner.style.setProperty('--v42-gap',`${clamp(e.target.value,0,200,14)}px`)});
 document.addEventListener('click',()=>setTimeout(refresh,0),true);
}
function buttonNode(n){return n?.matches?.('.web-btn')?n:n?.querySelector?.('.web-btn')}
function applyButton(n,o){const b=buttonNode(n);if(!b)return;b.classList.remove('v42-button-outline','v42-button-text','v42-btn-sm','v42-btn-lg');if(o.variant==='outline')b.classList.add('v42-button-outline');if(o.variant==='text')b.classList.add('v42-button-text');if(o.size==='sm')b.classList.add('v42-btn-sm');if(o.size==='lg')b.classList.add('v42-btn-lg');if(o.color!==undefined){b.style.setProperty('--v42-btn-color',o.color||'#705cff');if(!b.classList.contains('v42-button-outline')&&!b.classList.contains('v42-button-text')&&o.color)b.style.background=o.color}if(o.icon!==undefined){b.querySelectorAll(':scope>.v42-btn-icon').forEach(x=>x.remove());if(o.icon){const s=document.createElement('span');s.className='v42-btn-icon';s.textContent=o.icon;(o.pos==='left'?b.prepend.bind(b):b.append.bind(b))(s);b.dataset.v42Icon=o.icon;b.dataset.v42IconPos=o.pos||'right'}else{delete b.dataset.v42Icon;delete b.dataset.v42IconPos}}}
function makeNode(t){const n=document.createElement('div');n.className='custom-item';n.dataset.customType=t;if(t==='container'){n.classList.add('v42-container');n.innerHTML='<div class="v42-container-inner"></div>'}else if(t==='heading')n.innerHTML='<h2 contenteditable="true">New heading</h2>';else if(t==='text')n.innerHTML='<p contenteditable="true">New text</p>';else if(t==='image')n.innerHTML=`<img class="editable-image" src="${placeholderSvg('YOUR IMAGE')}" alt="Image" data-default="true">`;else if(t==='button')n.innerHTML='<a class="web-btn" href="#" contenteditable="true">Button</a>';else if(t==='divider')n.innerHTML='<hr class="content-divider">';return n}
function addNested(t){const s=findSection(state.selected);if(!s||s.type!=='custom')return;const b=boxFor(s),path=currentPath(),sel=path&&byPath(b,path);let target=b.querySelector('.custom-stack');if(sel?.classList.contains('v42-container'))target=sel.querySelector(':scope>.v42-container-inner');else if(sel?.closest?.('.v42-container'))target=sel.closest('.v42-container').querySelector(':scope>.v42-container-inner');if(!target)return;snapshot();target.appendChild(makeNode(t));s.html=b.innerHTML;commit();renderCanvas()}
function meaningful(n){return n.matches?.('.custom-item,.faq-item,.feature-card,.image-text-card,.stat-card,.testimonial-card,.pricing-card,.editable-image,.web-btn,h1,h2,h3,h4,h5,h6,p')&&!n.closest('.section-toolbar,.auto-page-nav')}
function layerLabel(n){const text=(n.innerText||n.alt||'').trim().replace(/\s+/g,' ').slice(0,28);return `${label(n)}${text?` · ${text}`:''}`}
function buildLayers(){const list=q('v42LayerList'),sec=sectionEl(),root=sec?.querySelector('.section-content');if(!list)return;if(!root){list.innerHTML='<small>Select a block</small>';return}const selected=liveSelected(),rows=[];function walk(node,depth){[...node.children].forEach(ch=>{const hit=meaningful(ch);if(hit){const p=pathOf(ch,root);rows.push({n:ch,p,depth});walk(ch,depth+1)}else walk(ch,depth)})}walk(root,0);list.innerHTML=rows.map((r,i)=>`<div class="v42-layer ${r.n===selected?'active':''}" draggable="${r.n.classList.contains('custom-item')?'true':'false'}" data-path="${r.p.join('.')}" style="--v42-depth:${r.depth}"><span class="v42-layer-indent"></span><span class="v42-layer-name">${escapeHtml(layerLabel(r.n))}</span><span class="v42-layer-actions">${r.n.classList.contains('custom-item')?`<button data-v42-layer="up">↑</button><button data-v42-layer="down">↓</button><button data-v42-layer="delete">×</button>`:''}</span></div>`).join('')||'<small>No editable layers</small>';bindLayers(root)}
function parsePath(s){return String(s||'').split('.').filter(x=>x!=='').map(Number)}
function bindLayers(root){let dragPath=null;q('v42LayerList').querySelectorAll('.v42-layer').forEach(row=>{row.onclick=e=>{if(e.target.closest('[data-v42-layer]'))return;const n=byPath(root,parsePath(row.dataset.path));if(n)n.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,view:window}))};const act=row.querySelector('[data-v42-layer]');row.querySelectorAll('[data-v42-layer]').forEach(b=>b.onclick=e=>{e.stopPropagation();layerAction(parsePath(row.dataset.path),b.dataset.v42Layer)});row.ondragstart=e=>{dragPath=parsePath(row.dataset.path);e.dataTransfer.effectAllowed='move'};row.ondragover=e=>{if(!dragPath)return;e.preventDefault();row.classList.add('drag-over')};row.ondragleave=()=>row.classList.remove('drag-over');row.ondrop=e=>{e.preventDefault();row.classList.remove('drag-over');if(dragPath)dropLayer(dragPath,parsePath(row.dataset.path),e.clientY,row.getBoundingClientRect());dragPath=null}})}
function layerAction(path,act){mutatePath(path,(n)=>{if(!n.classList.contains('custom-item'))return;if(act==='delete'){n.remove();return}const sib=[...n.parentElement.children],i=sib.indexOf(n),j=i+(act==='up'?-1:1);if(j<0||j>=sib.length)return;act==='up'?n.parentElement.insertBefore(n,sib[j]):n.parentElement.insertBefore(n,sib[j].nextSibling)})}
function dropLayer(srcPath,tgtPath,y,rect){const s=findSection(state.selected);if(!s||s.type!=='custom')return;const b=boxFor(s),src=byPath(b,srcPath),tgt=byPath(b,tgtPath);if(!src||!tgt||src===tgt||src.contains(tgt)||!src.classList.contains('custom-item'))return;snapshot();if(tgt.classList.contains('v42-container')){tgt.querySelector(':scope>.v42-container-inner')?.appendChild(src)}else{const before=y<rect.top+rect.height/2;tgt.parentElement.insertBefore(src,before?tgt:tgt.nextSibling)}s.html=b.innerHTML;commit();renderCanvas()}
function refresh(){const s=findSection(state.selected),n=liveSelected(),style=q('v42ElementStyle');if(!style)return;style.classList.toggle('hidden',!n);q('v42Nested').classList.toggle('hidden',s?.type!=='custom');buildLayers();if(!n)return;const cs=n.style;q('v42Bg').value=cs.background||'';[['v42Pt','paddingTop'],['v42Pr','paddingRight'],['v42Pb','paddingBottom'],['v42Pl','paddingLeft'],['v42Mt','marginTop'],['v42Mr','marginRight'],['v42Mb','marginBottom'],['v42Ml','marginLeft']].forEach(([id,p])=>q(id).value=parseFloat(cs[p])||'');q('v42Border').value=parseFloat(cs.borderWidth)||'';q('v42BorderColor').value=cs.borderColor||'';q('v42Radius').value=parseFloat(cs.borderRadius)||'';q('v42Opacity').value=cs.opacity===''||cs.opacity==null?100:Math.round(Number(cs.opacity)*100);q('v42Shadow').value=['v42-shadow-sm','v42-shadow-md','v42-shadow-lg'].find(c=>n.classList.contains(c))||'';
 const img=n.matches('.editable-image')?n:n.querySelector('.editable-image');q('v42Media').classList.toggle('hidden',!img);if(img){q('v42Ratio').value=img.style.getPropertyValue('--v42-ratio')||'';q('v42Position').value=img.style.objectPosition||'50% 50%'}const btn=buttonNode(n);q('v42Button').classList.toggle('hidden',!btn);if(btn){q('v42BtnVariant').value=btn.classList.contains('v42-button-outline')?'outline':btn.classList.contains('v42-button-text')?'text':'filled';q('v42BtnSize').value=btn.classList.contains('v42-btn-sm')?'sm':btn.classList.contains('v42-btn-lg')?'lg':'md';q('v42BtnColor').value=btn.style.getPropertyValue('--v42-btn-color')||'';q('v42BtnIcon').value=btn.dataset.v42Icon||'';q('v42BtnIconPos').value=btn.dataset.v42IconPos||'right'}
 const container=n.classList.contains('v42-container')?n:n.closest?.('.v42-container'),inner=container?.querySelector(':scope>.v42-container-inner');q('v42ContainerSettings').classList.toggle('hidden',!inner);if(inner){q('v42Dir').value=inner.style.getPropertyValue('--v42-dir')||'column';q('v42Gap').value=parseFloat(inner.style.getPropertyValue('--v42-gap'))||14;q('v42Align').value=inner.style.getPropertyValue('--v42-align')||'stretch';q('v42Justify').value=inner.style.getPropertyValue('--v42-justify')||'flex-start';q('v42Wrap').value=inner.style.getPropertyValue('--v42-wrap')||'wrap'}}
const exportCss=`.v42-container{min-height:40px;padding:14px;border-radius:12px}.v42-container-inner{display:flex;flex-direction:var(--v42-dir,column);flex-wrap:var(--v42-wrap,wrap);align-items:var(--v42-align,stretch);justify-content:var(--v42-justify,flex-start);gap:var(--v42-gap,14px)}.v42-container-inner>.custom-item{min-width:0;flex:0 1 var(--v4-item-w,auto)}.v42-button-outline{background:transparent!important;color:var(--v42-btn-color,#705cff)!important;border:2px solid var(--v42-btn-color,#705cff)!important}.v42-button-text{background:transparent!important;color:var(--v42-btn-color,#705cff)!important;border:0!important;box-shadow:none!important;padding-left:0!important;padding-right:0!important}.v42-btn-sm{padding:8px 13px!important;font-size:13px!important}.v42-btn-lg{padding:17px 27px!important;font-size:18px!important}.v42-btn-icon{display:inline-block;margin:0 7px}.v42-shadow-sm{box-shadow:0 4px 14px rgba(15,23,42,.12)!important}.v42-shadow-md{box-shadow:0 12px 32px rgba(15,23,42,.18)!important}.v42-shadow-lg{box-shadow:0 24px 60px rgba(15,23,42,.24)!important}.v42-ratio{width:100%;height:auto;aspect-ratio:var(--v42-ratio,auto);object-fit:var(--v42-fit,cover)}`;
const oldExport=exportedDocument;exportedDocument=page=>oldExport(page).replace('</head>',`<style id="v42-export">${exportCss}</style></head>`);
const oldRender=renderCanvas;renderCanvas=()=>{oldRender();setTimeout(refresh,0)};
const oldInspector=updateInspector;updateInspector=()=>{oldInspector();setTimeout(refresh,0)};
setTimeout(install,0);
})();
