(()=>{
const ex={ru:{heading:'Заголовок',image:'Изображение',stats:'Статистика',faq:'FAQ',custom:'Свой блок'},az:{heading:'Başlıq',image:'Şəkil',stats:'Statistika',faq:'FAQ',custom:'Öz blokun'},en:{heading:'Heading',image:'Image',stats:'Stats',faq:'FAQ',custom:'Custom block'}};
Object.entries(ex).forEach(([l,n])=>Object.assign(i18n[l].blocksNames,n));
const base=(o={})=>({bg:'#fff',color:'#111827',padding:64,paddingX:28,width:1120,align:'left',minHeight:0,radius:0,borderWidth:0,borderColor:'#dfe3ec',shadow:'none',...o});
Object.assign(templates,{
 heading:{icon:'H',category:'content',html:'<div class="kicker" contenteditable="true">РАЗДЕЛ</div><h2 contenteditable="true">Заголовок секции</h2><p contenteditable="true">Добавьте свой текст.</p>',style:base({width:880})},
 image:{icon:'▧',category:'content',html:`<img class="editable-image standalone-image" src="${placeholderSvg('YOUR IMAGE')}" alt="Image" data-default="true">`,style:base()},
 stats:{icon:'123',category:'content',html:'<div class="kicker" contenteditable="true">ЦИФРЫ</div><h2 contenteditable="true">Результаты</h2><div class="stats-grid"><article class="stat-card"><strong contenteditable="true">98%</strong><span contenteditable="true">метрика</span></article><article class="stat-card"><strong contenteditable="true">24/7</strong><span contenteditable="true">метрика</span></article><article class="stat-card"><strong contenteditable="true">3×</strong><span contenteditable="true">метрика</span></article></div>',style:base()},
 faq:{icon:'?',category:'content',html:'<div class="kicker" contenteditable="true">FAQ</div><h2 contenteditable="true">Частые вопросы</h2><div class="faq-list"><details class="faq-item" open><summary contenteditable="true">Вопрос 1</summary><p contenteditable="true">Ответ.</p></details><details class="faq-item"><summary contenteditable="true">Вопрос 2</summary><p contenteditable="true">Ответ.</p></details></div>',style:base({width:880})},
 custom:{icon:'＋',category:'main',html:'<div class="custom-stack"><div class="custom-item" data-custom-type="heading"><h2 contenteditable="true">Свой блок</h2></div><div class="custom-item" data-custom-type="text"><p contenteditable="true">Соберите блок под себя.</p></div></div>',style:base()}
});
state.dropIndex=null;state.draggedTemplate=null;state.pointerDrag=null;state.selectedElement=0;
function num(v,a,b,d){v=Number(v);return Number.isFinite(v)?Math.max(a,Math.min(b,Math.round(v))):d}
function norm(s){s.style||={};const t=templates[s.type]?.style||base();for(const[k,v]of Object.entries(t))if(s.style[k]===undefined)s.style[k]=clone(v);s.style.width=num(s.style.width,240,1920,1120);s.style.paddingX=num(s.style.paddingX,0,200,28);s.style.minHeight=num(s.style.minHeight,0,1600,0);s.style.radius=num(s.style.radius,0,120,0);s.style.borderWidth=num(s.style.borderWidth,0,12,0);s.style.borderColor||='#dfe3ec';s.style.shadow||='none';if(s.type==='navbar')menuify(s);return s}
function menuify(s){s.style.navDesktop||='inline';s.style.navMobileIcon||='☰';const b=document.createElement('div');b.innerHTML=s.html;const r=b.querySelector('.nav-row');if(!r)return;let t=r.querySelector('.nav-toggle');if(!t){t=document.createElement('button');t.type='button';t.className='nav-toggle';r.insertBefore(t,r.querySelector('.auto-page-nav,.nav-links')||r.lastChild)}t.textContent=s.style.navMobileIcon;r.classList.toggle('nav-desktop-dropdown',s.style.navDesktop==='dropdown');s.html=b.innerHTML}
const oldMake=makeSection;makeSection=t=>norm(oldMake(t));
function install(){const w=$('#contentWidth');if(w?.tagName==='SELECT'){const i=document.createElement('input');i.id='contentWidth';i.type='number';i.min=240;i.max=1920;i.step=1;w.replaceWith(i)}const f=$('#inspector');if(!f||$('#advancedLayoutControls'))return;const a=document.createElement('fieldset');a.id='advancedLayoutControls';a.className='image-controls';a.innerHTML='<legend>Layout</legend><label>Manual width<input id="manualWidth" type="number" min="240" max="1920"></label><div class="two-inputs"><label>Horizontal padding<input id="paddingX" type="number" min="0" max="200"></label><label>Min height<input id="minHeight" type="number" min="0" max="1600"></label></div><div class="two-inputs"><label>Radius<input id="sectionRadius" type="number" min="0" max="120"></label><label>Border<input id="borderWidth" type="number" min="0" max="12"></label></div>';const m=document.createElement('fieldset');m.id='menuControls';m.className='image-controls hidden';m.innerHTML='<legend>Menu</legend><label>Desktop<select id="menuDesktopMode"><option value="inline">Inline</option><option value="dropdown">Dropdown</option></select></label><label>Mobile icon<input id="menuMobileIcon" maxlength="4" value="☰"></label>';const c=document.createElement('fieldset');c.id='customBuilderControls';c.className='image-controls hidden';c.innerHTML='<legend>Custom block</legend><div class="custom-add-grid"><button type="button" data-add-custom="heading">+ Heading</button><button type="button" data-add-custom="text">+ Text</button><button type="button" data-add-custom="image">+ Image</button><button type="button" data-add-custom="button">+ Button</button><button type="button" data-add-custom="divider">+ Divider</button><button type="button" data-add-custom="spacer">+ Spacer</button></div><div id="customElementList"></div>';const acts=f.querySelector('.inspector-actions');f.insertBefore(a,acts);f.insertBefore(m,acts);f.insertBefore(c,acts);[['manualWidth','width',240,1920],['paddingX','paddingX',0,200],['minHeight','minHeight',0,1600],['sectionRadius','radius',0,120],['borderWidth','borderWidth',0,12]].forEach(([id,k,min,max])=>$('#'+id).oninput=e=>setStyle(k,num(e.target.value,min,max,0)));$('#menuDesktopMode').onchange=e=>setMenu('navDesktop',e.target.value);$('#menuMobileIcon').onchange=e=>setMenu('navMobileIcon',e.target.value||'☰');c.onclick=e=>{const b=e.target.closest('[data-add-custom]');if(b){e.preventDefault();addCustom(b.dataset.addCustom);return}const x=e.target.closest('[data-custom-action]');if(!x)return;const i=+x.dataset.index;if(x.dataset.customAction==='up')moveCustom(i,-1);if(x.dataset.customAction==='down')moveCustom(i,1);if(x.dataset.customAction==='delete')delCustom(i)}}
function outer(s){s=norm(s).style;return`background:${s.bg};color:${s.color};text-align:${s.align};border:${s.borderWidth}px solid ${s.borderColor};border-radius:${s.radius}px`}
function inner(s){s=norm(s).style;return`padding-top:${s.padding}px;padding-bottom:${s.padding}px;padding-left:${s.paddingX}px;padding-right:${s.paddingX}px;max-width:${s.width}px;min-height:${s.minHeight}px`}
renderCanvas=()=>{const ss=currentSections();ss.forEach(norm);canvas.classList.toggle('empty',!ss.length);canvas.innerHTML=ss.map(s=>`<section class="site-section ${s.id===state.selected?'selected':''}" data-id="${s.id}" style="${outer(s)}"><div class="section-toolbar"><button class="section-drag" type="button">↕</button><button data-act="up">↑</button><button data-act="down">↓</button><button data-act="duplicate">⧉</button><button data-act="delete">×</button></div><div class="section-content" style="${inner(s)}">${s.html}</div></section>`).join('');hydrateAutoNavigation(canvas,true);bindCanvas();updateInspector();updateHistoryButtons()};
function marker(i){removeMarkers();const m=document.createElement('div');m.className='drop-marker';const s=[...canvas.querySelectorAll(':scope>.site-section:not(.dragging)')];s[i]?canvas.insertBefore(m,s[i]):canvas.appendChild(m)}
dropIndexFromY=y=>{const a=[...canvas.querySelectorAll(':scope>.site-section:not(.dragging)')];for(let i=0;i<a.length;i++){const r=a[i].getBoundingClientRect();if(y<r.top+r.height/2)return i}return a.length}
function reorder(id,i){const s=currentSections(),o=s.findIndex(x=>x.id===id);if(o<0)return;snapshot();const[x]=s.splice(o,1);s.splice(Math.max(0,Math.min(i,s.length)),0,x);state.selected=id;commit();renderCanvas()}
function pointerDrag(el){const h=el.querySelector('.section-drag');let sx=0,sy=0,on=false,pid;h.onpointerdown=e=>{e.preventDefault();e.stopPropagation();sx=e.clientX;sy=e.clientY;pid=e.pointerId;state.pointerDrag=el.dataset.id;try{h.setPointerCapture(pid)}catch{}};h.onpointermove=e=>{if(state.pointerDrag!==el.dataset.id)return;if(!on&&Math.hypot(e.clientX-sx,e.clientY-sy)<5)return;on=true;el.classList.add('dragging');state.dropIndex=dropIndexFromY(e.clientY);marker(state.dropIndex)};const end=e=>{if(state.pointerDrag!==el.dataset.id)return;const id=state.pointerDrag,i=state.dropIndex;state.pointerDrag=null;el.classList.remove('dragging');removeMarkers();try{h.releasePointerCapture(pid)}catch{}if(on)reorder(id,i);on=false};h.onpointerup=end;h.onpointercancel=end;h.onclick=e=>{e.preventDefault();e.stopPropagation()}}
bindCanvas=()=>{$$('.site-section').forEach(el=>{el.onclick=e=>{const a=e.target.closest('[data-act]')?.dataset.act;if(a==='delete')return deleteSection(el.dataset.id);if(a==='duplicate')return duplicateSection(el.dataset.id);if(a==='up')return moveSection(el.dataset.id,-1);if(a==='down')return moveSection(el.dataset.id,1);state.selected=el.dataset.id;renderSelectionOnly()};pointerDrag(el)});$$('[contenteditable=true]').forEach(el=>{el.onfocus=()=>{state.selected=el.closest('.site-section').dataset.id;renderSelectionOnly()};el.oninput=debounce(()=>syncSectionHtml(el.closest('.site-section')),180)});$$('.auto-page-nav a').forEach(l=>l.onclick=e=>{e.preventDefault();e.stopPropagation();switchPage(l.dataset.pageId)});$$('.nav-toggle').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();b.closest('.nav-row')?.classList.toggle('nav-open')})};
canvas.ondragover=e=>{const t=e.dataTransfer?.getData('template')||state.draggedTemplate;if(!t)return;e.preventDefault();state.dropIndex=dropIndexFromY(e.clientY);marker(state.dropIndex)};canvas.ondrop=e=>{e.preventDefault();const i=state.dropIndex??dropIndexFromY(e.clientY),t=e.dataTransfer?.getData('template')||state.draggedTemplate;removeMarkers();state.dropIndex=null;if(t)addSection(t,i)};
renderLibrary=()=>{const q=$('#blockSearch').value.toLowerCase(),c=$('#categoryTabs .active')?.dataset.category||'all';$('#blockList').innerHTML=Object.entries(templates).filter(([k,t])=>(c==='all'||t.category===c)&&blockName(k).toLowerCase().includes(q)).map(([k,t])=>`<button class="block-card" draggable="true" data-template="${k}"><span class="block-icon">${t.icon}</span><strong>${escapeHtml(blockName(k))}</strong><small>${escapeHtml(tr('move'))}</small></button>`).join('');$$('.block-card').forEach(el=>{el.onclick=()=>addSection(el.dataset.template);el.ondragstart=e=>{state.draggedTemplate=el.dataset.template;e.dataTransfer?.setData('template',el.dataset.template)}})};
const oldInspector=updateInspector;updateInspector=()=>{oldInspector();const s=findSection(state.selected);if(!s)return;norm(s);$('#manualWidth').value=s.style.width;$('#paddingX').value=s.style.paddingX;$('#minHeight').value=s.style.minHeight;$('#sectionRadius').value=s.style.radius;$('#borderWidth').value=s.style.borderWidth;$('#menuControls').classList.toggle('hidden',s.type!=='navbar');if(s.type==='navbar'){$('#menuDesktopMode').value=s.style.navDesktop;$('#menuMobileIcon').value=s.style.navMobileIcon}$('#customBuilderControls').classList.toggle('hidden',s.type!=='custom');if(s.type==='custom')customList(s)};
function setStyle(k,v){const s=findSection(state.selected);if(!s)return;norm(s);s.style[k]=v;commit();renderCanvas()}function setMenu(k,v){const s=findSection(state.selected);if(!s||s.type!=='navbar')return;s.style[k]=v;menuify(s);commit();renderCanvas()}
function customBox(s){const b=document.createElement('div');b.innerHTML=s.html;return b}function customNode(t){const n=document.createElement('div');n.className='custom-item';n.dataset.customType=t;if(t==='heading')n.innerHTML='<h2 contenteditable="true">New heading</h2>';if(t==='text')n.innerHTML='<p contenteditable="true">New text</p>';if(t==='image')n.innerHTML=`<img class="editable-image" src="${placeholderSvg('YOUR IMAGE')}" alt="Image" data-default="true">`;if(t==='button')n.innerHTML='<a class="web-btn" href="#" contenteditable="true">Button</a>';if(t==='divider')n.innerHTML='<hr class="content-divider">';if(t==='spacer')n.innerHTML='<div style="height:72px"></div>';return n}function mutateCustom(fn){const s=findSection(state.selected);if(!s||s.type!=='custom')return;const b=customBox(s),st=b.querySelector('.custom-stack');snapshot();fn(st);s.html=b.innerHTML;commit();renderCanvas()}function addCustom(t){mutateCustom(st=>st.appendChild(customNode(t)))}function moveCustom(i,d){mutateCustom(st=>{const a=[...st.children],n=i+d;if(!a[i]||n<0||n>=a.length)return;d<0?st.insertBefore(a[i],a[n]):st.insertBefore(a[i],a[n].nextSibling)})}function delCustom(i){mutateCustom(st=>st.children[i]?.remove())}function customList(s){const a=[...customBox(s).querySelectorAll('.custom-stack>.custom-item')];$('#customElementList').innerHTML=a.map((x,i)=>`<div class="custom-element-row"><span>${i+1}. ${x.dataset.customType}</span><div><button data-custom-action="up" data-index="${i}">↑</button><button data-custom-action="down" data-index="${i}">↓</button><button data-custom-action="delete" data-index="${i}">×</button></div></div>`).join('')}
const extraCss='.nav-row{position:relative}.nav-toggle{display:none}.nav-desktop-dropdown .nav-toggle{display:inline-flex}.nav-desktop-dropdown .nav-links{display:none}.nav-desktop-dropdown.nav-open .nav-links{display:flex;position:absolute;right:0;top:100%;flex-direction:column;background:#fff;color:#111827;padding:12px;border-radius:10px}.stats-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:14px}.stat-card{padding:22px;border:1px solid #dfe3ec;border-radius:14px;background:#fff;color:#111827}.faq-list{display:grid;gap:10px}.faq-item{padding:16px;border:1px solid #dfe3ec;border-radius:12px;background:#fff;color:#111827}@media(max-width:760px){.nav-toggle{display:inline-flex}.nav-links{display:none}.nav-open .nav-links{display:flex;position:static;flex-direction:column}.stats-grid{grid-template-columns:1fr}}';
exportedDocument=page=>{page.sections.forEach(norm);const seo=page.seo,sections=page.sections.map(s=>`<section style="${outer(s)}"><div class="section-content" style="${inner(s)}">${cleanSectionHtml(s)}</div></section>`).join('\n');return `<!doctype html><html lang="${escapeAttr(page.lang)}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(seo.title||page.name)}</title><style>${SITE_CSS}${extraCss}</style></head><body>${sections}<script>document.querySelectorAll('.nav-toggle').forEach(b=>b.onclick=()=>b.closest('.nav-row').classList.toggle('nav-open'))<\/script></body></html>`};
install();const boot3=()=>{if(!state.project)return requestAnimationFrame(boot3);state.project.pages.forEach(p=>p.sections.forEach(norm));renderLibrary();renderAll();document.documentElement.dataset.builderVersion='3.0.0'};boot3();
})();
