import {uid} from './v5-model.mjs';
import {$,state,currentNode,mutate} from './v5-runtime.mjs';

function assets(){return state.project.assets||=([])}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function targetLabel(){const n=currentNode();if(!n)return'No selected element';if(n.type==='image')return'Use on selected Image';if(n.type==='logo')return'Use on selected Logo';if(n.type==='nav')return'Use as Menu logo';if(n.type==='gallery')return'Add to selected Gallery';return`Selected: ${n.type}`}
export function renderAssetManager(){const panel=$('#siteInspector');if(!panel)return;panel.querySelector('#v5AssetManager')?.remove();const list=assets();panel.insertAdjacentHTML('beforeend',`<fieldset id="v5AssetManager"><legend>Asset Manager</legend><div class="v5-assets-head"><label class="file-button">＋ Upload images<input id="v5AssetUpload" type="file" accept="image/*" multiple></label><small>${list.length} assets · ${targetLabel()}</small></div><div class="v5-assets-grid">${list.map(a=>`<article class="v5-asset"><img src="${esc(a.src)}" alt=""><input data-asset-name="${a.id}" value="${esc(a.name)}" title="Asset name"><small>${formatBytes(a.size||0)}</small><div><button type="button" data-asset-use="${a.id}">Use</button><button type="button" data-asset-delete="${a.id}" class="danger">×</button></div></article>`).join('')||'<div class="empty-inspector">No assets yet</div>'}</div></fieldset>`);injectCss()}
function injectCss(){if($('#v5AssetsCss'))return;const s=document.createElement('style');s.id='v5AssetsCss';s.textContent=`.v5-assets-head{display:grid;gap:7px;margin-bottom:10px}.v5-assets-head small{color:#8f9abb}.v5-assets-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.v5-asset{min-width:0;border:1px solid var(--line);border-radius:10px;padding:7px;background:#0b1120}.v5-asset img{width:100%;height:82px;object-fit:cover;border-radius:7px;background:#161d2e}.v5-asset input{margin:6px 0!important;padding:7px!important;font-size:11px}.v5-asset small{display:block;color:#8492b4;font-size:10px;margin-bottom:5px}.v5-asset>div{display:flex;gap:5px}.v5-asset button{min-height:30px!important;flex:1;padding:5px!important;font-size:11px}`;document.head.appendChild(s)}
export function bindAssetManager(){if(document.body.dataset.v5Assets==='1')return;document.body.dataset.v5Assets='1';$('#rightSidebar')?.addEventListener('change',async e=>{if(e.target.id==='v5AssetUpload'){await uploadAssets([...e.target.files||[]]);return}const n=e.target.closest('[data-asset-name]');if(n)mutate('Rename asset',()=>{const a=assets().find(x=>x.id===n.dataset.assetName);if(a)a.name=n.value.trim()||a.name})},true);$('#rightSidebar')?.addEventListener('click',e=>{const use=e.target.closest('[data-asset-use]');if(use){e.preventDefault();useAsset(use.dataset.assetUse);return}const del=e.target.closest('[data-asset-delete]');if(del){e.preventDefault();mutate('Delete asset',()=>state.project.assets=assets().filter(x=>x.id!==del.dataset.assetDelete));renderAssetManager()}},true)}
async function uploadAssets(files){if(!files.length)return;const out=[];for(const file of files){if(!file.type.startsWith('image/'))continue;const optimized=await optimize(file);out.push({id:uid('asset'),name:file.name.replace(/\.[^.]+$/,''),src:optimized.src,size:optimized.size,type:optimized.type,createdAt:new Date().toISOString()})}if(out.length)mutate('Upload assets',()=>assets().push(...out));renderAssetManager()}
async function optimize(file){if(file.type.includes('svg')||file.type.includes('gif'))return{src:await fileToData(file),size:file.size,type:file.type};try{const bmp=await createImageBitmap(file),max=2200,scale=Math.min(1,max/Math.max(bmp.width,bmp.height)),w=Math.max(1,Math.round(bmp.width*scale)),h=Math.max(1,Math.round(bmp.height*scale)),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(bmp,0,0,w,h);const blob=await new Promise(r=>c.toBlob(r,'image/webp',.84));if(blob)return{src:await fileToData(blob),size:blob.size,type:'image/webp'}}catch{}return{src:await fileToData(file),size:file.size,type:file.type}}
function fileToData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(file)})}
function useAsset(id){const a=assets().find(x=>x.id===id),n=currentNode();if(!a||!n)return alert('Select Image, Logo, Menu or Gallery first');if(n.type==='image')mutate('Use asset',()=>{n.props.src=a.src;if(!n.props.alt)n.props.alt=a.name});else if(n.type==='logo')mutate('Use asset',()=>{n.props.src=a.src;if(!n.props.alt)n.props.alt=a.name});else if(n.type==='nav')mutate('Use menu logo',()=>{n.props.logoImage=a.src;if(!n.props.logoAlt)n.props.logoAlt=a.name});else if(n.type==='gallery')mutate('Add gallery asset',()=>{n.props.items||=[];n.props.items.push({id:uid('img'),src:a.src,alt:a.name,caption:'',link:{type:'none',value:'',newTab:false,nofollow:false}})});else return alert('Select Image, Logo, Menu or Gallery first');renderAssetManager()}
function formatBytes(n){if(n<1024)return`${n} B`;if(n<1024*1024)return`${(n/1024).toFixed(0)} KB`;return`${(n/1024/1024).toFixed(1)} MB`}
