import {uid,clone,slugify,preset,walk,findNode,findNodeWithParent,moveNode,reorderBlocks,duplicateBlock,deleteBlock,pageFile,migrateProject} from './v5-model.mjs';
import {renderPage,collectCss,exportedDocument} from './v5-render.mjs';
import {$,$$,state,currentPage,currentBlock,currentNode,mutate,clearSelection,snapshot,persist,upgradeLegacyContent,undo,redo,esc} from './v5-runtime.mjs';
import {addElementType,elementFactories,elementLabels,createPageFlow,renderNavigator,navigatorClick,navigatorRename} from './v5-library.mjs';
import {elementCommand,uploadNodeImage} from './v5-element-actions.mjs';

export function renderCanvas(){const pg=currentPage(),canvas=$('#canvas');if(!canvas)return;canvas.innerHTML=renderPage(state.project,pg,{editor:true,selectedBlockId:state.selectedBlockId,selectedNodeId:state.selectedNodeId})||'<div class="empty-canvas">Add a block</div>';let style=$('#runtimeStyle');if(!style){style=document.createElement('style');style.id='runtimeStyle';document.head.appendChild(style)}style.textContent=collectCss(state.project,pg);canvas.dataset.device=state.device;$('#canvasFrame').className=`canvas-frame ${state.device}`;decorateCanvas()}
function decorateCanvas(){$$('#canvas .v5-node').forEach(el=>{if(el.dataset.locked!=='1')el.draggable=true;if(state.multi.has(el.dataset.nodeId))el.classList.add('v5-multi-selected')});$$('#canvas .v5-hidden').forEach(el=>el.classList.add('editor-show-hidden'))}
export function selectFromEvent(e){const sec=e.target.closest('[data-block-id]');if(!sec)return;const bid=sec.dataset.blockId,n=e.target.closest('[data-node-id]');if(n&&!e.target.closest('.v5-block-toolbar')){if((e.ctrlKey||e.metaKey)&&state.selectedBlockId===bid){state.multi.has(n.dataset.nodeId)?state.multi.delete(n.dataset.nodeId):state.multi.add(n.dataset.nodeId)}else{state.multi.clear();state.multi.add(n.dataset.nodeId)}state.selectedBlockId=bid;state.selectedNodeId=n.dataset.nodeId;state.activeRight='element'}else{state.multi.clear();state.selectedBlockId=bid;state.selectedNodeId='';state.activeRight='block'}state.render()}
export function beginInlineEdit(e){const n=e.target.closest('[data-node-id]');if(!n||!e.target.isContentEditable)return;state.editBefore=snapshot();state.editNodeId=n.dataset.nodeId}
export function inlineEdit(e){if(!state.editNodeId)return;const b=currentPage().blocks.find(x=>findNode(x.root,state.editNodeId));if(!b)return;const n=findNode(b.root,state.editNodeId),text=e.target.textContent;if(!n)return;if(['heading','text','button'].includes(n.type))n.props.text=text;persist()}
export function finishInlineEdit(){if(!state.editBefore)return;const after=snapshot();if(after!==state.editBefore){state.history.push({data:state.editBefore,label:'Edit text',time:Date.now()});if(state.history.length>80)state.history.shift();state.future=[]}state.editBefore=null;state.editNodeId='';state.render()}
export function blockToolbarClick(e){const btn=e.target.closest('[data-block-act]');if(!btn)return;e.preventDefault();e.stopPropagation();const id=btn.closest('[data-block-id]')?.dataset.blockId,pg=currentPage(),i=pg.blocks.findIndex(b=>b.id===id);if(i<0)return;if(btn.dataset.blockAct==='up'&&i>0)mutate('Move block',()=>{[pg.blocks[i-1],pg.blocks[i]]=[pg.blocks[i],pg.blocks[i-1]]});if(btn.dataset.blockAct==='down'&&i<pg.blocks.length-1)mutate('Move block',()=>{[pg.blocks[i+1],pg.blocks[i]]=[pg.blocks[i],pg.blocks[i+1]]});if(btn.dataset.blockAct==='duplicate')mutate('Duplicate block',()=>{const c=duplicateBlock(pg,id);state.selectedBlockId=c?.id||''});if(btn.dataset.blockAct==='delete')mutate('Delete block',()=>{deleteBlock(pg,id);clearSelection()})}

export function bindDnD(){
 document.addEventListener('dragstart',e=>{const libB=e.target.closest('[data-add-block]'),libE=e.target.closest('[data-add-element]'),treeB=e.target.closest('[data-tree-block]'),treeN=e.target.closest('[data-tree-node]'),canvasN=e.target.closest('#canvas [data-node-id]'),handle=e.target.closest('.v5-block-drag');if(libB)state.drag={kind:'new-block',key:libB.dataset.addBlock};else if(libE)state.drag={kind:'new-element',key:libE.dataset.addElement};else if(handle)state.drag={kind:'block',blockId:handle.closest('[data-block-id]').dataset.blockId};else if(treeB)state.drag={kind:'block',blockId:treeB.dataset.treeBlock};else if(treeN)state.drag={kind:'node',blockId:treeN.dataset.block,nodeId:treeN.dataset.treeNode};else if(canvasN&&!e.target.isContentEditable)state.drag={kind:'node',blockId:canvasN.closest('[data-block-id]').dataset.blockId,nodeId:canvasN.dataset.nodeId};if(state.drag&&e.dataTransfer){e.dataTransfer.effectAllowed=state.drag.kind.startsWith('new')?'copy':'move';e.dataTransfer.setData('text/plain',JSON.stringify(state.drag))}},true);
 document.addEventListener('dragend',()=>{state.drag=null;clearDropMarks()},true);
 $('#canvas').addEventListener('dragover',e=>{if(!state.drag)return;if(['node','new-element'].includes(state.drag.kind)){const pos=resolveElementDrop(e);if(!pos)return;e.preventDefault();clearDropMarks();if(pos.beforeId)pos.live.classList.add('drop-before');else if(pos.after)pos.live.classList.add('drop-after');else pos.containerLive.classList.add('drop-target')}else if(['block','new-block'].includes(state.drag.kind)){e.preventDefault();markBlockDrop(e.clientY)}},true);
 $('#canvas').addEventListener('drop',e=>{const d=state.drag;if(!d)return;if(['new-element','node'].includes(d.kind)){const pos=resolveElementDrop(e);if(!pos)return;e.preventDefault();e.stopPropagation();if(d.kind==='new-element')addElementAt(d.key,pos.blockId,pos.containerId,pos.beforeId);else moveNodeAcrossBlocks(d.blockId,d.nodeId,pos.blockId,pos.containerId,pos.beforeId)}else if(['new-block','block'].includes(d.kind)){e.preventDefault();const idx=blockDropIndex(e.clientY);if(d.kind==='new-block')mutate('Drop block',()=>{let b;if(d.key.startsWith('preset:')){const saved=state.project.presets.find(x=>x.id===d.key.slice(7));if(!saved)return;b=clone(saved.block);b.id=uid('block');walk(b.root,n=>n.id=uid('el'))}else b=preset(d.key);currentPage().blocks.splice(idx,0,b);state.selectedBlockId=b.id;state.selectedNodeId='';state.activeRight='block'});else mutate('Reorder block',()=>reorderBlocks(currentPage(),d.blockId,idx))}clearDropMarks();state.drag=null},true);
 $('#navigatorTree').addEventListener('dragover',e=>{if(!state.drag)return;const r=e.target.closest('[data-tree-node]');if(!r)return;const b=currentPage().blocks.find(x=>x.id===r.dataset.block),n=b&&findNode(b.root,r.dataset.treeNode);if(n?.type==='container'){e.preventDefault();clearDropMarks();r.classList.add('drop-target')}},true);
 $('#navigatorTree').addEventListener('drop',e=>{const r=e.target.closest('[data-tree-node]'),d=state.drag;if(!r||!d)return;const b=currentPage().blocks.find(x=>x.id===r.dataset.block),n=b&&findNode(b.root,r.dataset.treeNode);if(n?.type!=='container')return;e.preventDefault();if(d.kind==='new-element')addElementAt(d.key,b.id,n.id,'');else if(d.kind==='node')moveNodeAcrossBlocks(d.blockId,d.nodeId,b.id,n.id,'');clearDropMarks()},true);
 bindTouchDnD();
}
function resolveElementDrop(e){const live=e.target.closest('[data-node-id]');if(!live)return null;const sec=live.closest('[data-block-id]'),block=currentPage().blocks.find(x=>x.id===sec?.dataset.blockId),target=block&&findNode(block.root,live.dataset.nodeId);if(!block||!target)return null;if(target.type==='container'){const r=live.getBoundingClientRect(),edge=Math.min(24,r.height*.18);if(e.clientY>r.top+edge&&e.clientY<r.bottom-edge)return{blockId:block.id,containerId:target.id,beforeId:'',after:false,live,containerLive:live};const parentInfo=findNodeWithParent(block.root,target.id);if(parentInfo?.parent?.type==='container'){const siblings=parentInfo.parent.children,idx=siblings.findIndex(x=>x.id===target.id),after=e.clientY>=r.top+r.height/2,beforeId=after?(siblings[idx+1]?.id||''):target.id;return{blockId:block.id,containerId:parentInfo.parent.id,beforeId,after,live,containerLive:live.closest('.v5-container')}}return{blockId:block.id,containerId:target.id,beforeId:'',after:false,live,containerLive:live}}const info=findNodeWithParent(block.root,target.id);if(!info?.parent||info.parent.type!=='container')return null;const r=live.getBoundingClientRect(),siblings=info.parent.children,idx=siblings.findIndex(x=>x.id===target.id),after=e.clientY>=r.top+r.height/2,beforeId=after?(siblings[idx+1]?.id||''):target.id;return{blockId:block.id,containerId:info.parent.id,beforeId,after,live,containerLive:live.parentElement?.closest('.v5-container')}}
function addElementAt(type,blockId,containerId,beforeId=''){mutate('Add element',()=>{const b=currentPage().blocks.find(x=>x.id===blockId),c=b&&findNode(b.root,containerId),factory=elementFactories[type];if(!b||c?.type!=='container'||!factory)return;const el=factory(),idx=beforeId?c.children.findIndex(x=>x.id===beforeId):-1;idx>=0?c.children.splice(idx,0,el):c.children.push(el);state.selectedBlockId=b.id;state.selectedNodeId=el.id;state.multi.clear();state.multi.add(el.id);state.activeRight='element'})}
function moveNodeAcrossBlocks(srcBlockId,nodeId,targetBlockId,targetId,beforeId=''){mutate('Move element',()=>{const src=currentPage().blocks.find(x=>x.id===srcBlockId),dst=currentPage().blocks.find(x=>x.id===targetBlockId);if(!src||!dst)return;if(src===dst){if(!moveNode(src,nodeId,targetId,beforeId))return;state.selectedBlockId=dst.id;state.selectedNodeId=nodeId;return}const found=findNodeWithParent(src.root,nodeId),target=findNode(dst.root,targetId);if(!found?.parent||target?.type!=='container'||target.locked)return;found.parent.children=found.parent.children.filter(x=>x.id!==nodeId);const idx=beforeId?target.children.findIndex(x=>x.id===beforeId):-1;idx>=0?target.children.splice(idx,0,found.node):target.children.push(found.node);state.selectedBlockId=dst.id;state.selectedNodeId=nodeId})}
function nodeByLive(el){const b=currentPage().blocks.find(x=>x.id===el.closest('[data-block-id]')?.dataset.blockId);return b?findNode(b.root,el.dataset.nodeId):null}
function markBlockDrop(y){clearDropMarks();const secs=$$('#canvas>[data-block-id]'),i=blockDropIndex(y),m=document.createElement('div');m.className='block-drop-marker';secs[i]?$('#canvas').insertBefore(m,secs[i]):$('#canvas').appendChild(m)}
function blockDropIndex(y){const secs=$$('#canvas>[data-block-id]');for(let i=0;i<secs.length;i++){const r=secs[i].getBoundingClientRect();if(y<r.top+r.height/2)return i}return secs.length}
function clearDropMarks(){$$('.drop-target,.drop-before,.drop-after').forEach(x=>x.classList.remove('drop-target','drop-before','drop-after'));$$('.block-drop-marker').forEach(x=>x.remove())}

function bindTouchDnD(){let timer=null,drag=null;$('#canvas').addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'||e.target.isContentEditable||e.target.closest('button,a,input,textarea,select'))return;const n=e.target.closest('[data-node-id]');if(!n)return;timer=setTimeout(()=>{drag={blockId:n.closest('[data-block-id]').dataset.blockId,nodeId:n.dataset.nodeId};n.classList.add('touch-dragging');try{n.setPointerCapture(e.pointerId)}catch{}},350)},true);$('#canvas').addEventListener('pointermove',e=>{if(!drag)return;e.preventDefault();clearDropMarks();const hit=document.elementFromPoint(e.clientX,e.clientY),c=hit?.closest?.('.v5-container[data-node-id]');if(c)c.classList.add('drop-target')},true);const end=e=>{clearTimeout(timer);timer=null;if(!drag)return;const hit=document.elementFromPoint(e.clientX,e.clientY),c=hit?.closest?.('.v5-container[data-node-id]');if(c)moveNodeAcrossBlocks(drag.blockId,drag.nodeId,c.closest('[data-block-id]').dataset.blockId,c.dataset.nodeId);$$('.touch-dragging').forEach(x=>x.classList.remove('touch-dragging'));drag=null;clearDropMarks()};$('#canvas').addEventListener('pointerup',end,true);$('#canvas').addEventListener('pointercancel',end,true)}

export function openContextMenu(e){const nodeEl=e.target.closest('[data-node-id],[data-tree-node]'),blockEl=e.target.closest('[data-block-id],[data-tree-block]');if(!nodeEl&&!blockEl)return;e.preventDefault();if(nodeEl){state.selectedNodeId=nodeEl.dataset.nodeId||nodeEl.dataset.treeNode;const be=nodeEl.closest('[data-block-id],[data-tree-block]');state.selectedBlockId=be?.dataset.blockId||be?.dataset.treeBlock||nodeEl.dataset.block||state.selectedBlockId;state.activeRight='element'}else{state.selectedBlockId=blockEl.dataset.blockId||blockEl.dataset.treeBlock;state.selectedNodeId='';state.activeRight='block'}state.render();const m=$('#contextMenu');m.style.left=Math.min(e.clientX,innerWidth-170)+'px';m.style.top=Math.min(e.clientY,innerHeight-220)+'px';m.classList.remove('hidden')}
export function contextAction(e){const b=e.target.closest('[data-context]');if(!b)return;const c=b.dataset.context;if(state.selectedNodeId){if(c==='duplicate')elementCommand('duplicate');if(c==='copy')elementCommand('copy');if(c==='copy-style')elementCommand('copy-style');if(c==='paste-style')elementCommand('paste-style');if(c==='delete')elementCommand('delete')}else if(state.selectedBlockId){if(c==='duplicate')blockToolbarCommand('duplicate');if(c==='delete')blockToolbarCommand('delete')}$('#contextMenu').classList.add('hidden')}
function blockToolbarCommand(cmd){const b=currentBlock();if(!b)return;if(cmd==='duplicate')mutate('Duplicate block',()=>{const c=duplicateBlock(currentPage(),b.id);state.selectedBlockId=c?.id||''});if(cmd==='delete')mutate('Delete block',()=>{deleteBlock(currentPage(),b.id);clearSelection()})}

export function keyboardShortcuts(e){if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='c'&&state.selectedNodeId&&!e.target.matches('input,textarea,[contenteditable=true]')){state.clipboard=clone(currentNode());e.preventDefault()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='v'&&state.clipboard&&!e.target.matches('input,textarea,[contenteditable=true]')){elementCommand('paste');e.preventDefault()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'&&!e.target.matches('input,textarea,[contenteditable=true]')){e.preventDefault();if(state.selectedNodeId)elementCommand('duplicate');else blockToolbarCommand('duplicate')}if(e.key==='Delete'&&!e.target.matches('input,textarea,[contenteditable=true]')){if(state.selectedNodeId)elementCommand('delete');else blockToolbarCommand('delete')}}

export function openPreview(){const pg=currentPage();$('#previewPage').innerHTML=state.project.pages.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('#previewPage').value=pg.id;renderPreview(pg.id);$('#previewDialog').showModal()}
export function renderPreview(id){const p=state.project.pages.find(x=>x.id===id)||currentPage();$('#previewFrame').srcdoc=exportedDocument(state.project,p)}
export async function downloadSite(){if(!window.JSZip){downloadBlob(new Blob([exportedDocument(state.project,currentPage())],{type:'text/html'}),pageFile(currentPage()));return}const zip=new JSZip();for(const p of state.project.pages)zip.file(pageFile(p),exportedDocument(state.project,p));if(state.project.notFoundPageId){const nf=state.project.pages.find(p=>p.id===state.project.notFoundPageId);if(nf)zip.file('404.html',exportedDocument(state.project,nf))}zip.file('robots.txt',robotsText());zip.file('sitemap.xml',sitemapXml());zip.file('project.json',JSON.stringify(state.project,null,2));const blob=await zip.generateAsync({type:'blob'});downloadBlob(blob,`${slugify(state.project.name)||'website'}-v5.zip`)}
function robotsText(){const base=state.project.siteUrl?`\nSitemap: ${state.project.siteUrl.replace(/\/$/,'')}/sitemap.xml`:'';return`User-agent: *\nAllow: /${base}\n`}
function sitemapXml(){const base=(state.project.siteUrl||'https://example.com').replace(/\/$/,'');return`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${state.project.pages.filter(p=>!p.seo.noindex).map(p=>`<url><loc>${esc(base+'/'+pageFile(p))}</loc></url>`).join('')}</urlset>`}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
export function importProject(file){if(!file)return;file.text().then(text=>{try{const p=migrateProject(JSON.parse(text));mutate('Import project',()=>{state.project=p;upgradeLegacyContent(state.project);clearSelection()})}catch{alert('Invalid project')}})}
