import {uid,clone,preset,container,makeHeading,makeText,makeButton,makeImage,makeSpacer,makeDivider,makeIcon,makeList,makeVideo,makeEmbed,makeSocial,makeLogo,makeTable,makeMap,makeCounter,makeAccordion,makeTabs,makeHtml,makeForm,makeReviews,walk,findNode,addPage} from './v5-model.mjs';
import {$,$$,state,tr,currentPage,currentBlock,currentNode,currentParent,mutate,clearSelection,esc,attr} from './v5-runtime.mjs';
import {CUSTOM_SECTION_TYPES,customSectionLabel,makeCustomSection} from './v6-custom-sections.mjs';
import {FUNCTIONAL_READY_TYPES,FUNCTIONAL_ICONS,makeFunctionalPreset} from './v6-functional-blocks.mjs';
import {PREMIUM_READY_TYPES,PREMIUM_BLOCK_META,makePremiumPreset} from './v6-premium-blocks.mjs';
import {installPremiumLibraryStyles} from './v6-premium-library.mjs';
export const readyTypes=['navbar','hero','features','text','split','imageText','gallery','cards','quote','cta','contact','footer','faq','stats','testimonials','pricing','logos',...PREMIUM_READY_TYPES,...FUNCTIONAL_READY_TYPES];
export const layoutTypes=['layout1','layout2','layout3','layout4'];
export const elementFactories={heading:()=>makeHeading('Heading',2),text:()=>makeText('Text'),image:()=>makeImage('','Image'),button:()=>makeButton('Button'),divider:()=>makeDivider(),spacer:()=>makeSpacer(),icon:()=>makeIcon(),list:()=>makeList(),video:()=>makeVideo(),embed:()=>makeEmbed('<iframe src="https://example.com" title="Embed"></iframe>'),social:()=>makeSocial(),logo:()=>makeLogo(),table:()=>makeTable(),map:()=>makeMap(),counter:()=>makeCounter(),accordion:()=>makeAccordion(),tabs:()=>makeTabs(),form:()=>makeForm(),reviews:()=>makeReviews(),html:()=>makeHtml('<div>Custom HTML</div>'),container:()=>container()};
export const elementLabels={heading:'Heading',text:'Text',image:'Image',button:'Button',divider:'Divider',spacer:'Spacer',icon:'Icon',list:'List',video:'Video',embed:'Embed',social:'Social',logo:'Logo',table:'Table',map:'Map',counter:'Counter',accordion:'Accordion',tabs:'Tabs',form:'Form',reviews:'Reviews slider',html:'HTML',container:'Container',nav:'Navigation',gallery:'Gallery'};
export function iconFor(t){if(t.startsWith('custom-'))return CUSTOM_SECTION_TYPES.find(x=>x.type===t)?.icon||'＋';if(PREMIUM_BLOCK_META[t]?.icon)return PREMIUM_BLOCK_META[t].icon;if(FUNCTIONAL_ICONS[t])return FUNCTIONAL_ICONS[t];return t.includes('layout')?'▦':({navbar:'☰',hero:'✦',features:'▦',text:'¶',split:'◧',imageText:'▤',gallery:'▧',cards:'▦',quote:'“',cta:'→',contact:'@',footer:'⌄',faq:'?',stats:'123',testimonials:'★',pricing:'₼',logos:'LOGO'}[t]||'＋')}
export function iconForElement(k){return({heading:'H',text:'¶',image:'▧',button:'▣',divider:'—',spacer:'↕',icon:'★',list:'☷',video:'▶',embed:'<>',social:'◎',logo:'L',table:'▦',map:'⌖',counter:'123',accordion:'?',tabs:'⊞',form:'✉',reviews:'★',html:'</>',container:'▯'}[k]||'+')}
export function renderLeft(){['blocks','elements','pages'].forEach(n=>{$(`#${n}Panel`).classList.toggle('hidden',state.activeLeft!==n);$(`#${n}Tab`).classList.toggle('active',state.activeLeft===n)});if(state.activeLeft==='blocks')renderBlocksLibrary();if(state.activeLeft==='elements')renderElementsLibrary();if(state.activeLeft==='pages')renderPagesList()}
export function renderBlocksLibrary(){installPremiumLibraryStyles();const q=($('#blockSearch').value||'').toLowerCase(),cat=$('#blockCategory').value||'ready',lang=state.project?.uiLang||'en';let items=[];if(cat==='ready')items=readyTypes.map(type=>{const meta=PREMIUM_BLOCK_META[type];const b=meta?makePremiumPreset(type):FUNCTIONAL_READY_TYPES.includes(type)?makeFunctionalPreset(type):preset(type);return{type,name:meta?.name||b?.name||type,description:meta?.description||'',badge:meta?.badge||'',family:meta?.family||'',premium:!!meta}});else if(cat==='layouts')items=layoutTypes.map(type=>({type,name:preset(type).name}));else if(cat==='custom')items=CUSTOM_SECTION_TYPES.map(x=>({type:x.type,name:customSectionLabel(x.type,lang)}));else items=(state.project.presets||[]).map(x=>({type:'preset:'+x.id,name:x.name}));items=items.filter(x=>`${x.name} ${x.description||''} ${x.family||''}`.toLowerCase().includes(q));$('#blockList').innerHTML=items.map(x=>`<button class="library-card${x.premium?' is-premium':''}" type="button" draggable="true" data-add-block="${x.type}"${x.family?` data-block-family="${attr(x.family)}"`:''}><span>${iconFor(x.type)}</span>${x.badge?`<em class="v6-premium-badge">${esc(x.badge)}</em>`:''}<strong>${esc(x.name)}</strong>${x.description?`<small>${esc(x.description)}</small>`:''}</button>`).join('')||'<small>Empty</small>'}
export function renderElementsLibrary(){const q=($('#elementSearch').value||'').toLowerCase();$('#elementList').innerHTML=Object.keys(elementFactories).filter(k=>elementLabels[k].toLowerCase().includes(q)).map(k=>`<button class="library-card" type="button" draggable="true" data-add-element="${k}"><span>${iconForElement(k)}</span><strong>${elementLabels[k]}</strong></button>`).join('')}
export function renderPagesList(){$('#pageList').innerHTML=`<button id="addPageInline" class="primary wide" type="button">${tr('addPage')}</button>`+state.project.pages.map(p=>`<button class="page-row ${p.id===state.project.currentPageId?'active':''}" data-page-id="${p.id}"><span>${p.home?'★ ':''}${esc(p.name)}</span><small>${p.home?'index.html':esc(p.slug+'.html')}</small></button>`).join('')}
export function addBlockFromLibrary(key){mutate('Add block',()=>{let b;if(key.startsWith('preset:')){const p=state.project.presets.find(x=>x.id===key.slice(7));if(!p)return;b=clone(p.block);b.id=uid('block');walk(b.root,n=>n.id=uid('el'))}else if(key.startsWith('custom-'))b=makeCustomSection(key,state.project?.uiLang||'en');else if(PREMIUM_READY_TYPES.includes(key))b=makePremiumPreset(key);else if(FUNCTIONAL_READY_TYPES.includes(key))b=makeFunctionalPreset(key);else b=preset(key);if(!b)return;const pg=currentPage(),idx=pg.blocks.findIndex(x=>x.id===state.selectedBlockId);pg.blocks.splice(idx<0?pg.blocks.length:idx+1,0,b);state.selectedBlockId=b.id;state.selectedNodeId='';state.multi.clear();state.activeRight='block'})}
export function targetContainer(){const n=currentNode();if(n?.type==='container')return n;const p=currentParent();if(p?.type==='container')return p;return currentBlock()?.root?.type==='container'?currentBlock().root:null}
export function addElementType(type,targetId=''){mutate('Add element',()=>{let b=currentBlock(),c=targetId&&b?findNode(b.root,targetId):targetContainer();if(!b||!c){b=preset('layout1');currentPage().blocks.push(b);state.selectedBlockId=b.id;c=b.root}const el=elementFactories[type]?.();if(!el)return;c.children.push(el);state.selectedNodeId=el.id;state.multi.clear();state.multi.add(el.id);state.activeRight='element'})}
export function createPageFlow(){const name=prompt('Page name','New page');if(!name)return;mutate('Create page',()=>{const p=addPage(state.project,name,state.project.uiLang);state.project.currentPageId=p.id;clearSelection();state.activeRight='page'})}
export function renderNavigator(){const pg=currentPage(),root=$('#navigatorTree');root.innerHTML=pg.blocks.map(b=>navBlockRow(b)).join('')}
function navBlockRow(b){const collapsed=state.collapsed.has(b.id);return`<div class="tree-block" data-tree-block="${b.id}" draggable="true"><div class="tree-row ${b.id===state.selectedBlockId&&!state.selectedNodeId?'active':''}"><button data-collapse="${b.id}">${collapsed?'▸':'▾'}</button><span data-tree-select-block="${b.id}">${esc(b.name)}</span><small>${esc(b.anchor?'#'+b.anchor:b.preset||'section')}</small></div>${collapsed?'':`<div class="tree-children">${treeNodeRows(b,b.root,0)}</div>`}</div>`}
function treeNodeRows(b,n,depth){const row=`<div class="tree-row node ${n.id===state.selectedNodeId||state.multi.has(n.id)?'active':''}" data-tree-node="${n.id}" data-block="${b.id}" draggable="${n.locked?'false':'true'}" style="--depth:${depth}"><span class="tree-indent"></span><span data-tree-select-node="${n.id}" data-block="${b.id}">${esc(n.name||elementLabels[n.type]||n.type)}</span>${n.hidden?'<small>◌</small>':''}${n.locked?'<small>🔒</small>':''}</div>`;return row+(n.children||[]).map(c=>treeNodeRows(b,c,depth+1)).join('')}
export function navigatorClick(e){const c=e.target.closest('[data-collapse]');if(c){const id=c.dataset.collapse;state.collapsed.has(id)?state.collapsed.delete(id):state.collapsed.add(id);renderNavigator();return}const b=e.target.closest('[data-tree-select-block]');if(b){state.multi.clear();state.selectedBlockId=b.dataset.treeSelectBlock;state.selectedNodeId='';state.activeRight='block';state.render();return}const n=e.target.closest('[data-tree-select-node]');if(n){if((e.ctrlKey||e.metaKey)&&state.selectedBlockId===n.dataset.block){state.multi.has(n.dataset.treeSelectNode)?state.multi.delete(n.dataset.treeSelectNode):state.multi.add(n.dataset.treeSelectNode)}else{state.multi.clear();state.multi.add(n.dataset.treeSelectNode)}state.selectedBlockId=n.dataset.block;state.selectedNodeId=n.dataset.treeSelectNode;state.activeRight='element';state.render()}}
export function navigatorRename(e){const n=e.target.closest('[data-tree-node]'),b=e.target.closest('[data-tree-block]');if(n){const block=currentPage().blocks.find(x=>x.id===n.dataset.block),node0=block&&findNode(block.root,n.dataset.treeNode);if(!node0)return;const name=prompt('Element name',node0.name||elementLabels[node0.type]||node0.type);if(name!==null)mutate('Rename element',()=>node0.name=name.trim())}else if(b){const block=currentPage().blocks.find(x=>x.id===b.dataset.treeBlock);if(!block)return;const name=prompt('Block name',block.name);if(name!==null)mutate('Rename block',()=>block.name=name.trim()||block.name)}}
export function bindLibraryUi(){$('#blockSearch').oninput=renderBlocksLibrary;$('#blockCategory').onchange=renderBlocksLibrary;$('#elementSearch').oninput=renderElementsLibrary;$('#blocksPanel').onclick=e=>{const b=e.target.closest('[data-add-block]');if(b)addBlockFromLibrary(b.dataset.addBlock)};$('#elementsPanel').onclick=e=>{const b=e.target.closest('[data-add-element]');if(b)addElementType(b.dataset.addElement)};$('#pagesPanel').onclick=e=>{const r=e.target.closest('[data-page-id]');if(r){state.project.currentPageId=r.dataset.pageId;clearSelection();state.activeRight='page';state.render()}if(e.target.id==='addPageInline')createPageFlow()};$('#navigatorTree').onclick=navigatorClick;$('#navigatorTree').ondblclick=navigatorRename}
