import {block,container,makeNav,makeText,makeHeading,makeButton,makeImage,makeIcon,makeSocial,makeLogo,makeAccordion,makeGallery,makeImageTextGrid} from './v5-core.mjs';
export function preset(type){const b=(name,root)=>block(name,root);switch(type){
case'navbar':{const x=b('Menu',container([makeNav()],{gap:0}));x.preset='navbar';x.style.base.paddingTop='18px';x.style.base.paddingBottom='18px';return x}
case'hero':{const left=container([makeText('NEW GENERATION'),makeHeading('Создавай смело. Запускай быстро.',1),makeText('Профессиональный сайт без сложного кода — собери страницу из готовых блоков.'),makeButton('Начать проект')],{gap:18}),right=container([makeImage('','Hero image')]),root=container([left,right],{direction:'row',gap:36});root.style.base.display='grid';root.style.base.gridTemplateColumns='1.15fr .85fr';root.style.tablet.gridTemplateColumns='1fr 1fr';root.style.mobile.gridTemplateColumns='1fr';const x=b('Hero',root);x.preset='hero';x.style.base.background='linear-gradient(135deg,#f7f3ff,#fff0e8)';x.style.base.paddingTop='84px';x.style.base.paddingBottom='84px';return x}
case'features':{const titles=['Быстрый запуск','Адаптивный дизайн','Полный контроль'],descs=['Соберите страницу за несколько минут.','Отличный вид на любом устройстве.','Скачайте код и разместите где угодно.'],cards=[1,2,3].map(i=>container([makeIcon(`0${i}`),makeHeading(titles[i-1],3),makeText(descs[i-1])],{gap:10}));cards.forEach(c=>Object.assign(c.style.base,{padding:'22px',border:'1px solid #dfe3ec',borderRadius:'16px'}));const grid=container(cards,{gap:16});grid.style.base.display='grid';grid.style.base.gridTemplateColumns='repeat(3,minmax(0,1fr))';grid.style.tablet.gridTemplateColumns='repeat(2,minmax(0,1fr))';grid.style.mobile.gridTemplateColumns='1fr';return b('Features',container([makeText('ПОЧЕМУ МЫ'),makeHeading('Всё необходимое для сильного старта',2),grid],{gap:20}))}
case'text':return b('Text',container([makeText('НАША ИСТОРИЯ'),makeHeading('Простая идея, сильный результат',2),makeText('Нажмите на любой текст и начните редактирование. Все изменения сохраняются в вашем браузере.')],{gap:16}));
case'split':{const image=container([makeImage('','Section image')]),text=container([makeText('О ПРОЕКТЕ'),makeHeading('Дизайн, который работает',2),makeText('Расскажите о продукте понятным языком и покажите его главное преимущество.'),makeButton('Подробнее')],{gap:16}),root=container([image,text],{gap:32});root.style.base.display='grid';root.style.base.gridTemplateColumns='1fr 1fr';root.style.mobile.gridTemplateColumns='1fr';return b('Text + Image',root)}
case'imageText':return b('Image + Text',container([makeText('КОЛЛЕКЦИЯ'),makeHeading('Изображения с текстом',2),makeImageTextGrid(6)],{gap:18}));
case'gallery':return b('Gallery',container([makeText('ГАЛЕРЕЯ'),makeHeading('Наши работы',2),makeGallery(6)],{gap:18}));
case'cards':{const cards=[1,2,3].map(i=>container([makeImage('',`Card ${i}`),makeHeading(`Заголовок ${i}`,3),makeText('Краткое описание элемента.'),makeButton('Подробнее')],{gap:12}));cards.forEach(c=>Object.assign(c.style.base,{padding:'16px',border:'1px solid #dfe3ec',borderRadius:'16px'}));const grid=container(cards,{gap:16});grid.style.base.display='grid';grid.style.base.gridTemplateColumns='repeat(3,minmax(0,1fr))';grid.style.tablet.gridTemplateColumns='repeat(2,minmax(0,1fr))';grid.style.mobile.gridTemplateColumns='1fr';return b('Cards',container([makeText('КАРТОЧКИ'),makeHeading('Изображения с описанием',2),grid],{gap:18}))}
case'quote':{const x=b('Quote',container([makeHeading('«Хороший сайт не просто выглядит красиво — он ясно ведёт человека к нужному действию».',2),makeText('— ВАША КОМАНДА')],{gap:14}));x.style.base.background='#18152c';x.style.base.color='#fff';return x}
case'cta':{const x=b('CTA',container([makeHeading('Готовы начать?',2),makeText('Соберите страницу и скачайте готовый сайт.'),makeButton('Начать')],{gap:16,align:'center'}));x.style.base.background='#705cff';x.style.base.color='#fff';return x}
case'contact':return b('Contact',container([makeText('КОНТАКТЫ'),makeHeading('Свяжитесь с нами',2),makeText('hello@example.com · +994 00 000 00 00'),makeSocial()],{gap:16}));
case'footer':{const root=container([makeLogo('NOVA'),makeText('© 2026. Все права защищены.'),makeSocial()],{direction:'row',justify:'space-between',align:'center',gap:16});root.style.mobile.flexDirection='column';const x=b('Footer',root);x.style.base.background='#111827';x.style.base.color='#fff';x.style.base.paddingTop='28px';x.style.base.paddingBottom='28px';return x}
case'faq':return b('FAQ',container([makeText('FAQ'),makeHeading('Частые вопросы',2),makeAccordion()],{gap:18}));
case'stats':{const cards=['98%','24/7','3×'].map((v,i)=>container([makeHeading(v,2),makeText(['метрика','поддержка','рост'][i])],{gap:6})),grid=container(cards,{gap:14});grid.style.base.display='grid';grid.style.base.gridTemplateColumns='repeat(3,minmax(0,1fr))';grid.style.mobile.gridTemplateColumns='1fr';return b('Stats',container([makeText('ЦИФРЫ'),makeHeading('Результаты',2),grid],{gap:18}))}
case'testimonials':{const cards=[1,2,3].map(i=>container([makeText('★★★★★'),makeText(`Отзыв клиента ${i}.`),makeHeading(`Клиент ${i}`,3)],{gap:8})),grid=container(cards,{gap:14});grid.style.base.display='grid';grid.style.base.gridTemplateColumns='repeat(3,minmax(0,1fr))';grid.style.mobile.gridTemplateColumns='1fr';return b('Testimonials',container([makeHeading('Отзывы',2),grid],{gap:18}))}
case'pricing':{const cards=[['Start','49'],['Pro','99'],['Plan 3','147']].map(([n,p],i)=>{const c=container([makeHeading(n,3),makeHeading(`${p} ₼`,2),makeText('Краткое описание тарифа.'),makeButton('Выбрать')],{gap:14});Object.assign(c.style.base,{padding:'28px',border:i===1?'2px solid #705cff':'1px solid #dfe3ec',borderRadius:'16px'});return c}),grid=container(cards,{gap:16});grid.style.base.display='grid';grid.style.base.gridTemplateColumns='repeat(3,minmax(0,1fr))';grid.style.tablet.gridTemplateColumns='repeat(2,minmax(0,1fr))';grid.style.mobile.gridTemplateColumns='1fr';return b('Pricing',container([makeHeading('Тарифы',2),grid],{gap:20}))}
case'logos':{const grid=container(['LOGO 1','LOGO 2','LOGO 3','LOGO 4'].map(x=>makeLogo(x,'')),{gap:16,align:'center'});grid.style.base.display='grid';grid.style.base.gridTemplateColumns='repeat(4,minmax(0,1fr))';grid.style.mobile.gridTemplateColumns='repeat(2,minmax(0,1fr))';return b('Logos',grid)}
case'layout1':return b('Container',container([],{}));
case'layout2':{const r=container([container(),container()],{gap:20});r.style.base.display='grid';r.style.base.gridTemplateColumns='1fr 1fr';r.style.mobile.gridTemplateColumns='1fr';return b('2 Columns',r)}
case'layout3':{const r=container([container(),container(),container()],{gap:20});r.style.base.display='grid';r.style.base.gridTemplateColumns='repeat(3,minmax(0,1fr))';r.style.tablet.gridTemplateColumns='repeat(2,minmax(0,1fr))';r.style.mobile.gridTemplateColumns='1fr';return b('3 Columns',r)}
case'layout4':{const r=container([container(),container(),container(),container()],{gap:20});r.style.base.display='grid';r.style.base.gridTemplateColumns='repeat(4,minmax(0,1fr))';r.style.tablet.gridTemplateColumns='repeat(2,minmax(0,1fr))';r.style.mobile.gridTemplateColumns='1fr';return b('4 Columns',r)}
default:return b('Section',container())}}