import test from 'node:test';import assert from 'node:assert/strict';
import {defaultProject,preset,addPage,moveNode,node,container,makeButton,migrateProject,auditProject,reorderBlocks,duplicateNode,pageFile} from '../v5-model.mjs';
import {exportedDocument} from '../v5-render.mjs';

test('project schema and page slug',()=>{const p=defaultProject();assert.equal(p.schemaVersion,5);const a=addPage(p,'О компании','ru');assert.equal(a.slug,'o-kompanii');const b=addPage(p,'О компании','ru');assert.equal(b.slug,'o-kompanii-2');assert.equal(pageFile(p.pages[0]),'index.html')});
test('container move uses stable IDs',()=>{const p=defaultProject(),b=preset('layout2');p.pages[0].blocks.push(b);const [c1,c2]=b.root.children;const btn=makeButton('Go');c1.children.push(btn);assert.equal(moveNode(b,btn.id,c2.id),true);assert.equal(c2.children[0].id,btn.id)});
test('block reorder',()=>{const p=defaultProject(),pg=p.pages[0],id=pg.blocks[0].id;reorderBlocks(pg,id,pg.blocks.length);assert.equal(pg.blocks.at(-1).id,id)});
test('duplicate node renews IDs',()=>{const b=preset('layout1'),btn=makeButton('A');b.root.children.push(btn);const c=duplicateNode(b,btn.id);assert.notEqual(c.id,btn.id)});
test('legacy migration preserves content as editable-safe html node',()=>{const legacy={version:2,name:'Old',pages:[{id:'p',name:'Главная',home:true,lang:'ru',seo:{},sections:[{id:'s',type:'text',html:'<h2>Hello</h2>',style:{bg:'#fff',color:'#111',padding:10,width:800}}]}],currentPageId:'p'};const p=migrateProject(legacy);assert.equal(p.schemaVersion,5);assert.equal(p.pages[0].blocks[0].root.children[0].type,'html')});
test('functional path add link export',()=>{const p=defaultProject(),pg=p.pages[0],b=preset('layout1');pg.blocks.push(b);const btn=makeButton('Open');btn.props.link={type:'url',value:'example.com',newTab:true,nofollow:false};b.root.children.push(btn);const html=exportedDocument(p,pg);assert.match(html,/https:\/\/example\.com/);assert.match(html,/target="_blank"/)});
test('audit detects missing alt',()=>{const p=defaultProject(),b=preset('layout1');p.pages[0].blocks.push(b);b.root.children.push(node('image',{src:'x',alt:''}));const issues=auditProject(p);assert.ok(issues.some(x=>/ALT/.test(x.msg)))});
test('global header propagates to every page',async()=>{const mod=await import('../v5-model.mjs');const p=mod.defaultProject();mod.addPage(p,'Second','en');const h=mod.preset('navbar');h.name='Global Nav';mod.setGlobal(p,'header',h);for(const pg of p.pages){assert.equal(pg.blocks[0].globalRole,'header');assert.equal(pg.blocks[0].name,'Global Nav')}});
test('responsive CSS is exported from the same model',async()=>{const {collectCss}=await import('../v5-render.mjs');const p=defaultProject(),pg=p.pages[0],b=preset('layout1');b.root.style.mobile.width='50%';pg.blocks.push(b);const css=collectCss(p,pg);assert.match(css,/max-width:760px/);assert.match(css,/width:50%/)});
test('audit catches duplicate anchor',()=>{const p=defaultProject(),pg=p.pages[0],a=preset('text'),b=preset('text');a.anchor='x';b.anchor='x';pg.blocks.push(a,b);assert.ok(auditProject(p).some(x=>/Duplicate anchor/.test(x.msg)))});
test('moveNode prevents moving a container into its own descendant',()=>{const b=preset('layout1'),outer=b.root.children[0]||b.root,inner=container();outer.children.push(inner);assert.equal(moveNode(b,outer.id,inner.id),false)});
